import {CONFIG} from './config.js';
import {createState,step,install,retrieve,nearSocket,restoreArchive,results,setBrightness,setGravity,activeSocket,hasCard,here,sector,speed,TIMING,FRAGMENTS} from './src/model.js';
const SYMBOL=['○','△','◇'],CARD_NAMES=['brightness','gravity'],TOTAL_FRAGMENTS=FRAGMENTS.length;
import {ArchiveAudio} from './src/audio.js';
import {ANIMATIONS} from './src/animations.js';
import {initTutorial} from './src/tutorial.js';
const $=id=>document.getElementById(id);const reducedQuery=matchMedia('(prefers-reduced-motion: reduce)');
let manualTouch=false,videoEpoch=0;
let settings={master:80,music:65,effects:80,sensitivity:50,mute:false,reduced:reducedQuery.matches,touch:matchMedia('(pointer:coarse)').matches||innerWidth<700,invert:false};
try{const saved=JSON.parse(localStorage.getItem('ctrl-reality-settings')||'{}');manualTouch=!!saved.manualTouch;for(const k of Object.keys(settings))if((k!=='touch'||manualTouch)&&typeof saved[k]===typeof settings[k])settings[k]=typeof saved[k]==='number'?Math.max(0,Math.min(100,saved[k])):saved[k];}catch{}
initTutorial();
const sound=new ArchiveAudio();sound.apply(settings);let state=createState(),screen='title',returnScreen='title',archive,keys=new Set(),joystick={x:0,z:0},drag=null,selected=false,animUntil=0,toastUntil=0,startAt=0,startLatency=null,transitionUntil=0,cameraYaw=0,cameraPitch=0,footTimer=0,clock=0;
function applySettings(){document.body.classList.toggle('touch',settings.touch);sound.apply(settings);for(const [key,value]of Object.entries(settings)){const el=$(key);if(!el)continue;if(el.type==='checkbox')el.checked=value;else{el.value=value;document.querySelector(`output[for="${key}"]`).value=value+'%';}}if(settings.reduced)stopVideo();try{localStorage.setItem('ctrl-reality-settings',JSON.stringify({...settings,manualTouch}));}catch{}}
applySettings();
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');toastUntil=performance.now()+2600;}
function cancelInput(){sound.drag(false);keys.clear();joystick.x=joystick.z=0;$('stick').style.transform='';if(drag){drag=null;$('drag-card').hidden=true;}selected=false;}
let focusBefore=null;
function show(next,{focus=true}={}){const previous=screen;screen=next;toastUntil=0;$('toast').classList.remove('visible');document.body.dataset.screen=next;document.querySelectorAll('.screen').forEach(el=>el.hidden=el.id!==next);cancelInput();if(previous==='title'&&next!=='title')stopVideo();if(next==='title'){sound.stopShots();sound.setMode('title');startVideo();archive?.animator.set('TITLE_IDLE');}else if(next==='hud'){sound.setMode('game');if(previous==='pause')sound.play('pause-close',{bus:'UI_SFX'});}else if(next==='pause'){sound.setMode('pause');sound.play('pause-open',{bus:'UI_SFX'});}else if(next==='results'){sound.stopShots();sound.setMode('results');}
 if(focus&&next!=='hud')requestAnimationFrame(()=>$(next).querySelector('button,input')?.focus({preventScroll:true}));
}
function openPanel(name){sound.play('ui-open',{bus:'UI_SFX'});focusBefore=document.activeElement;returnScreen=screen;show(name);}
function back(){sound.play('ui-back',{bus:'UI_SFX'});sound.play('ui-close',{bus:'UI_SFX',volume:.35});const target=returnScreen;show(target);if(focusBefore?.isConnected)focusBefore.focus({preventScroll:true});}
function stopVideo(){videoEpoch++;const v=$('title-video');v.pause();v.removeAttribute('src');v.load();v.style.opacity='0';}
async function startVideo(){if(!CONFIG.USE_TITLE_VIDEO||innerWidth<=700||new URLSearchParams(location.search).has('gate')||settings.reduced||navigator.connection?.saveData||(navigator.deviceMemory&&navigator.deviceMemory<4)||screen!=='title')return;
 const v=$('title-video'),epoch=++videoEpoch;
 if(!v.getAttribute('src'))v.src=v.canPlayType('video/webm; codecs="vp9"')?'./media/title/title-desktop-loop.webm':'./media/title/title-desktop-loop.mp4';
 v.onloadeddata=()=>{if(screen==='title'&&epoch===videoEpoch)v.play().then(()=>{if(screen==='title'&&epoch===videoEpoch)v.style.opacity='1';}).catch(()=>{v.style.opacity='0';});};v.load();
}
const poster=$('poster');function markPoster(){if(poster.naturalWidth)window.__POSTER_VISIBLE__=performance.now();}if(poster.complete)markPoster();else poster.addEventListener('load',markPoster,{once:true});
$('title-video').addEventListener('error',()=>{$('title-video').style.opacity='0';});
function animate(name,duration=.8){archive?.animator.set(name);animUntil=clock+duration;}
// Briefings: one when the Atrium opens, one when the Kernel yields the second control. Both time from a sector start.
let pendingStart=false,startRequestedAt=0,briefed=false,briefing=null;
function endBriefing(){if(!briefing)return;$(briefing.id).hidden=true;briefing=null;document.body.classList.remove('briefing');}
function startBriefing(id){endBriefing();briefing={id,at:state.elapsed};$(id).hidden=false;document.body.classList.add('briefing');$(id).querySelectorAll('[data-line]').forEach(el=>el.classList.remove('shown'));}
function begin(){if(!archive)sound.mode='silent';sound.unlock();if(!pendingStart)startRequestedAt=performance.now();if(!archive){pendingStart=true;$('startb').setAttribute('aria-busy','true');$('startb').firstChild.textContent='Opening the archive ';return;}pendingStart=false;$('startb').removeAttribute('aria-busy');$('startb').firstChild.textContent='Enter the archive ';state=createState();document.body.dataset.restoring='false';$('hud').inert=false;$('restoration').hidden=true;archive.snapCamera();startAt=startRequestedAt;startLatency=null;show('hud',{focus:false});$('failure').hidden=true;animate('IDLE',0);transitionUntil=performance.now()+(settings.reduced?300:1000);$('transition').classList.add('active');setTimeout(()=>$('transition').classList.remove('active'),settings.reduced?40:110);
 if(briefed)toast('The archive has gone dark again. Carry the light.');else{briefed=true;startBriefing('briefing');}}
const cardLabel=card=>card==='gravity'?'GRAVITY':'BRIGHTNESS';
const installedOf=card=>card==='gravity'?state.gInstalled:state.installed;
const socketOf=card=>card==='gravity'?state.gSocket:state.installedSocket;
function changeBrightness(level){if(!setBrightness(state,level)){if(screen==='hud'&&!state.failure&&!state.won&&!state.restoration)toast(here(state,'brightness')?'Walk back to the socket to change the light.':state.stage>=3&&state.stage<5?'BRIGHTNESS waits. This part of the Well needs GRAVITY.':'Install BRIGHTNESS in a socket first.');return;}sound.play('ui-tick',{bus:'UI_SFX'});
 if(state.stage===0&&level==='RADIANT'){sound.play('bridge-energy');animate('BRIDGE_REVEAL_REACTION',1.85);toast(`The bridge is forming. RADIANT holds ${TIMING.surge} seconds. Cross before it fades.`);}
 else if(state.stage===1&&!state.readSolved)toast(level==='DIM'?'Remember the order on the plates. Then press 2 and walk it.':level==='BALANCED'?(state.glyphSeen?'Walk the three plates in order. Do not stop between them.':'The plates are dark. Press 1 to see their order.'):'Too bright to read. The far edge is now dangerous.');
 else if(state.stage===2&&state.cleared.length<3)toast(level==='DIM'?'The fractures glow. Remember where they are, then press 2.':level==='BALANCED'?(state.nodesSeen?`Walk into each fracture. Seal all three within ${TIMING.hold} seconds.`:'Press 1 to find the fractures first.'):'Too bright. Touching a fracture now will throw you back.');
 else if(state.stage===2&&state.cleared.length===3&&level!=='RADIANT')toast('All sealed. Press 3 to restore the Kernel.');
 else if(state.stage===5)toast(level==='DIM'?(here(state,'gravity')&&state.gravity==='HEAVY'?'The locks show. Walk onto all three.':'DIM alone shows nothing here. Add HEAVY gravity with 6.'):level==='RADIANT'?(state.locks.length===3?'Now LOW gravity with 4, then walk onto the core.':'Too bright. The deck edges burn until the locks are set.'):'BALANCED. Nothing burns, nothing shows.');
 if(restoreArchive(state))startRestoration();}
function changeGravity(level){if(!setGravity(state,level)){if(screen==='hud'&&!state.failure&&!state.won&&!state.restoration)toast(!state.hasGravity?'You do not hold GRAVITY yet.':here(state,'gravity')?'Walk back to the socket to change gravity.':'Install GRAVITY in a violet socket first.');return;}sound.play('ui-tick',{bus:'UI_SFX'});
 if(state.stage===3)toast(level==='LOW'?`The slabs are rising. LOW lasts ${TIMING.lowCharge} seconds and you walk slowly. Go.`:level==='HEAVY'?'HEAVY sinks the slabs. LOW lifts them.':'NORMAL. The slabs settle back.');
 else if(state.stage===4)toast(level==='HEAVY'?(state.anchored?'The anchors hold. The stair to the core is open.':`The anchors freeze. Pin all three before the deck crumbles, about ${TIMING.crumble} seconds.`):level==='LOW'?'The anchors float. They cannot be pinned like this.':'NORMAL. The anchors drift and the deck heals.');
 else if(state.stage===5)toast(level==='HEAVY'?(here(state,'brightness')&&state.brightness==='DIM'?'The locks show. Walk onto all three.':state.locksSeen?'Walk onto the three locks.':'HEAVY alone shows nothing here. Add DIM light with 1.'):level==='LOW'?(state.locks.length===3&&here(state,'brightness')&&state.brightness==='RADIANT'?`The core is rising. Step onto it within ${TIMING.lowCharge} seconds.`:state.locks.length===3?'LOW spends fast. Set RADIANT with 3 first.':'The locks must be set before the core will answer.'):'NORMAL. Nothing moves.');}
document.querySelectorAll('[data-level]').forEach(b=>b.addEventListener('click',()=>changeBrightness(b.dataset.level)));
document.querySelectorAll('[data-gravity]').forEach(b=>b.addEventListener('click',()=>changeGravity(b.dataset.gravity)));
function pause(){if(screen!=='hud'||state.restoration||state.won)return;show('pause');}
// The card E acts on: the selected one if it is near its socket, else a card still in hand, else the nearest installed one.
function cardHere(){const near=CARD_NAMES.filter(c=>hasCard(state,c)&&nearSocket(state,c));if(!near.length)return null;if(selected&&near.includes(selected))return selected;const d=c=>{const k=activeSocket(state,c);return Math.hypot(state.x-k.x,state.z-k.z);};return near.sort((a,b)=>(installedOf(a)-installedOf(b))||(d(a)-d(b)))[0];}
function act(){if(screen!=='hud'||state.failure||state.won||state.restoration)return;sound.unlock();if(restoreArchive(state)){startRestoration();return;}const card=cardHere();
 if(card){if(installedOf(card)){const wasHere=here(state,card);retrieve(state,card);animate('CONTROL_RETRIEVE');sound.play('control-retrieve');toast(wasHere?`${cardLabel(card)} is back in your hand.`:`${cardLabel(card)} is back in your hand. Press E again to install it here.`);}else installControl(card);}
 else toast(state.stage>=3&&!state.gInstalled?'Walk to the violet socket for GRAVITY.':state.installed||state.gInstalled?'Walk to the next glowing socket.':'Walk to the glowing socket, then press E or drag the card.');}
function installControl(card='brightness'){if(!install(state,card)){sound.play('control-invalid');toast(hasCard(state,card)?'Bring Mara closer to the socket.':'You do not hold that control yet.');return false;}selected=false;animate('CONTROL_DEPLOY',1.2);sound.play('control-socket');setTimeout(()=>{if(screen==='hud'&&state.installed&&state.brightness==='RADIANT')sound.play('bridge-reveal');},350);endBriefing();
 toast(card==='gravity'?(state.stage===3?'Installed. Press 4 for LOW to lift the slabs.':state.stage===4?'Installed. Press 6 for HEAVY to freeze the anchors.':'Installed. DIM light (1) plus HEAVY gravity (6) shows the locks.'):state.stage===0?'Installed. Press 3 for RADIANT to build the bridge.':state.stage===1?'Installed. Press 1 for DIM to see the plate order.':state.stage===2?'Installed. Press 1 for DIM to find the fractures.':'Installed. Now GRAVITY in the socket beside it.');return true;}
function startRestoration(){animate('VICTORY_IDLE',100);cancelInput();document.body.dataset.restoring='true';$('hud').inert=true;const kernel=state.stage===2;$('restoration-kicker').textContent=kernel?'THE KERNEL REMEMBERS':'THE ARCHIVE REMEMBERS';$('restoration-title').textContent=kernel?'Kernel restored.':'Reality stable.';$('restoration').hidden=false;sound.play('victory');}
// The Kernel gives back BRIGHTNESS and yields GRAVITY. Sector 02 opens below it.
function descend(){document.body.dataset.restoring='false';$('hud').inert=false;$('restoration').hidden=true;animate('CHECKPOINT');sound.play('checkpoint');sound.play('control-pickup');startBriefing('briefing-well');}
function win(){animate('VICTORY_IDLE',100);const r=results(state);$('result-time').textContent=Math.floor(r.seconds/60).toString().padStart(2,'0')+':'+(r.seconds%60).toString().padStart(2,'0');for(const k of ['resets','moves','rank'])$('result-'+k).textContent=r[k];$('result-missteps').textContent=state.missteps;$('result-fragments').textContent=r.fragments+' / '+TOTAL_FRAGMENTS;$('result-efficiency').textContent=r.efficiency+'%';setTimeout(()=>{if(state.won){$('restoration').hidden=true;show('results');}},1400);}
$('startb').addEventListener('click',begin);$('replay').addEventListener('click',begin);$('resume').addEventListener('click',()=>show('hud',{focus:false}));$('pause-button').addEventListener('click',pause);$('act').addEventListener('click',act);
$('restart').addEventListener('click',()=>{show('hud',{focus:false});state.failure=.001;sound.play('failure-fracture');animate('REALIGN_FAILURE',1.3);});
document.querySelectorAll('[data-open]').forEach(el=>el.addEventListener('click',()=>{sound.unlock();openPanel(el.dataset.open);}));document.querySelectorAll('.back').forEach(el=>el.addEventListener('click',back));document.querySelectorAll('.return-title').forEach(el=>el.addEventListener('click',()=>{endBriefing();state=createState();document.body.dataset.restoring='false';$('hud').inert=false;$('restoration').hidden=true;$('failure').hidden=true;show('title');}));
document.querySelectorAll('button').forEach(b=>{b.addEventListener('pointerenter',()=>sound.play('ui-hover',{bus:'UI_SFX',volume:.35}));b.addEventListener('click',()=>{sound.unlock();sound.play('ui-confirm',{bus:'UI_SFX'});});});
for(const k of Object.keys(settings))$(k)?.addEventListener('input',e=>{if(k==='touch')manualTouch=true;settings[k]=e.target.type==='checkbox'?e.target.checked:Number(e.target.value);applySettings();sound.unlock();sound.play(e.target.type==='checkbox'?'ui-toggle':'ui-tick',{bus:'UI_SFX',volume:.5});});
reducedQuery.addEventListener('change',e=>{settings.reduced=e.matches;applySettings();});
window.addEventListener('keydown',e=>{const key=e.key.toLowerCase();if(key==='tab'&&screen!=='hud'){const controls=[...$(screen).querySelectorAll('button:not(:disabled),input')];const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}return;}
 if(key==='escape'){e.preventDefault();if(screen==='hud')pause();else if(screen==='pause')show('hud',{focus:false});else if(['settings','how','creation'].includes(screen))back();return;}
 if(screen!=='hud'||e.repeat)return;if(['1','2','3'].includes(key)){changeBrightness(['DIM','BALANCED','RADIANT'][Number(key)-1]);return;}if(['4','5','6'].includes(key)){changeGravity(['LOW','NORMAL','HEAVY'][Number(key)-4]);return;}if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(key))e.preventDefault();if(key==='e'){act();return;}keys.add(key);});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
window.addEventListener('blur',()=>{cancelInput();if(screen==='hud')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelInput();if(screen==='hud')pause();sound.context?.suspend();stopVideo();}else if(screen==='title')startVideo();});
$('world').addEventListener('pointermove',e=>{if(screen!=='hud'||e.pointerType==='touch'||!e.buttons)return;cameraYaw=Math.max(-.38,Math.min(.38,cameraYaw-e.movementX*.0015*settings.sensitivity/50));cameraPitch=Math.max(-.5,Math.min(.5,cameraPitch+e.movementY*.001*(settings.invert?-1:1)));});
const joy=$('joystick');let joyId=null;function moveJoy(e){const r=joy.getBoundingClientRect();const dx=e.clientX-(r.x+r.width/2),dy=e.clientY-(r.y+r.height/2),l=Math.hypot(dx,dy),scale=Math.min(1,38/(l||1));joystick.x=dx*scale/38;joystick.z=dy*scale/38;$('stick').style.transform=`translate(${dx*scale}px,${dy*scale}px)`;}
joy.addEventListener('pointerdown',e=>{if(screen!=='hud')return;joyId=e.pointerId;joy.setPointerCapture(joyId);moveJoy(e);sound.unlock();});joy.addEventListener('pointermove',e=>{if(e.pointerId===joyId)moveJoy(e);});for(const event of ['pointerup','pointercancel','lostpointercapture'])joy.addEventListener(event,()=>{joyId=null;joystick.x=joystick.z=0;$('stick').style.transform='';});
// Both control cards drag the same way: pick up, carry to the matching socket, release. The drag ghost shows the card's own symbol.
function bindCard(card,name){card.addEventListener('pointerdown',e=>{if(screen!=='hud'||state.failure||!hasCard(state,name))return;sound.unlock();if(installedOf(name)){toast(settings.touch?'The card is in a socket. Press ACT there to take it back.':'The card is in a socket. Press E there to take it back.');return;}drag={id:e.pointerId,x:e.clientX,y:e.clientY,moved:false,card:name};card.setPointerCapture(e.pointerId);selected=name;animate('CONTROL_PULL');sound.play('control-pickup');sound.drag(true);});
 card.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>8)drag.moved=true;if(drag.moved){$('drag-card').hidden=false;$('drag-card').textContent=name==='gravity'?'⊕':'☼';$('drag-card').classList.toggle('gravity',name==='gravity');$('drag-card').style.left=e.clientX+'px';$('drag-card').style.top=e.clientY+'px';animate('CONTROL_DRAG',.1);const p=archive.socketScreen(name);const valid=nearSocket(state,name)&&Math.hypot(e.clientX-p.x,e.clientY-p.y)<85;if(valid&&!$('socket-target').classList.contains('valid'))sound.play('socket-valid');$('socket-target').classList.toggle('valid',valid);}});
 card.addEventListener('pointerup',e=>{if(!drag)return;const d=drag;sound.drag(false);drag=null;$('drag-card').hidden=true;$('socket-target').classList.remove('valid');if(d.moved){const p=archive.socketScreen(name);if(Math.hypot(e.clientX-p.x,e.clientY-p.y)<85&&nearSocket(state,name))installControl(name);else{sound.play('control-invalid');toast(nearSocket(state,name)?'Release over the glowing socket.':`Walk Mara to the ${name==='gravity'?'violet':'cyan'} socket first, then drag.`);animate('IDLE');}}else{selected=name;toast(settings.touch?`${cardLabel(name)} selected. Press ACT at the socket.`:`${cardLabel(name)} selected. Press E at the socket.`);}});card.addEventListener('pointercancel',()=>{sound.drag(false);drag=null;selected=false;$('drag-card').hidden=true;});card.addEventListener('click',e=>{if(e.detail===0&&!installedOf(name)&&hasCard(state,name)){selected=name;toast(`${cardLabel(name)} selected. Press E at the socket.`);}});}
const card=$('brightness'),gravityCard=$('gravity');bindCard(card,'brightness');bindCard(gravityCard,'gravity');
window.addEventListener('resize',()=>{archive?.resize();cancelInput();if(!manualTouch){settings.touch=matchMedia('(pointer:coarse)').matches||innerWidth<700;applySettings();}});window.addEventListener('pagehide',()=>sound.teardown());
let review=null,reviewState='IDLE',reviewSpeed=1;if(new URLSearchParams(location.search).has('review')){review='front';const el=document.createElement('div');el.className='review-controls';el.innerHTML='<label>Animation <select id="review-state">'+ANIMATIONS.map(a=>`<option>${a}</option>`).join('')+'</select></label><label>View <select id="review-view"><option value="front">Front</option><option value="side">Side</option><option value="rear">Rear three-quarter</option></select></label><label>Speed <select id="review-speed"><option value="1">1×</option><option value="0.5">½×</option></select></label>';$('interface').append(el);$('review-state').onchange=e=>{reviewState=e.target.value;archive.animator.set(reviewState);};$('review-view').onchange=e=>review=e.target.value;$('review-speed').onchange=e=>reviewSpeed=Number(e.target.value);}
window.__INTERFACE_READY__=true;
show('title',{focus:false});
const secs=v=>Math.max(0,Math.ceil(v));
try{const {createArchive}=await import('./src/scene.js');archive=await createArchive($('world'));if(pendingStart)begin();if(review){document.querySelectorAll('.screen').forEach(el=>el.hidden=true);$('title-media').style.display='none';stopVideo();archive.animator.set(reviewState);}
 let previous=performance.now(),accumulator=0,bridgeComplete=false,lastSegment=0;function frame(now){const dt=Math.min(.05,(now-previous)/1000);previous=now;clock+=dt;accumulator+=dt;
  while(accumulator>=CONFIG.STEP){if(screen==='hud'&&!review){const input={x:(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0)+joystick.x,z:(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0)+joystick.z};if(drag)input.x=input.z=0;const events=step(state,input,CONFIG.STEP);for(const event of events){if(event==='victory'){win();}if(event==='kernel-restored'){descend();}if(event==='failure'){animate('REALIGN_FAILURE',1.3);sound.stopShots();sound.play('failure-fracture');setTimeout(()=>{if(state.failure)sound.play('failure-reverse');},180);}if(event==='collapse')toast('The deck gave way. HEAVY held too long.');if(event==='reset'){sound.play('checkpoint');toast('Back at the last checkpoint.');}if(event==='fragment'){sound.play('fragment');toast(`Fragment found. ${state.fragments.length} / ${TOTAL_FRAGMENTS}`);}if(event==='checkpoint'){animate('CHECKPOINT');sound.play('checkpoint');endBriefing();toast(state.stage===1?'Checkpoint. The gallery: find the socket on the right.':state.stage===2?'Checkpoint. The Kernel: find its socket ahead.':state.stage===3?'Checkpoint. The landing. The slabs ahead are sunk in the pit.':state.stage===4?'Checkpoint. The anchor deck. GRAVITY belongs in the socket here now.':'Checkpoint. The core. Two sockets, side by side.');}
     if(event==='glyph'){sound.play('socket-valid');toast(`${SYMBOL[state.glyphInput.at(-1)]} accepted. Plate ${state.glyphInput.length} of 3.`);}if(event==='misstep'){sound.play('control-invalid');toast('Wrong plate. The order resets. Press 1 at the socket to see it again.');}if(event==='read-solved'){animate('CHECKPOINT');sound.play('checkpoint');toast('Order restored. The way down is open.');}if(event==='plates-cooled'){sound.play('control-invalid');toast('The plates cooled. Start the order again.');}
     if(event==='node'){sound.play('control-socket');animate('CONTROL_DEPLOY',.6);toast(state.cleared.length===3?'All three sealed. Back to the socket, then press 3.':`Fracture sealed. ${state.cleared.length} / 3. Seal the rest in ${secs(TIMING.hold-state.holdTimer)} seconds.`);}if(event==='fractures-reopened'){sound.play('failure-fracture');toast('Too slow. The fractures reopened.');}if(event==='surge-spent'){sound.play('ui-toggle',{bus:'UI_SFX'});toast('RADIANT faded to BALANCED. The bridge is retracting.');}
     if(event==='charge-spent'){sound.play('ui-toggle',{bus:'UI_SFX'});toast('LOW gravity spent. Back to NORMAL.');}if(event==='lift-ready'){sound.play('bridge-complete');toast('The slabs are up. Cross now.');}if(event==='anchor'){sound.play('control-socket');animate('CONTROL_DEPLOY',.6);toast(`Anchor pinned. ${state.pins.filter(Boolean).length} / 3`);}if(event==='anchored'){sound.play('checkpoint');toast('All three anchors hold. The stair to the core is open.');}if(event==='lock'){sound.play('socket-valid');toast(`Lock set. ${state.locks.length} / 3`);}if(event==='locked'){sound.play('checkpoint');toast('Locks set. Now RADIANT light (3) and LOW gravity (4). Then step onto the core.');}if(event==='core-ready'){sound.play('bridge-complete');toast('The core is up. Step onto it.');}if(event==='sync'){startRestoration();}}
   if(startLatency===null)startLatency=performance.now()-startAt;if(state.moving&&!state.failure){footTimer+=CONFIG.STEP;if(footTimer>.4){footTimer=0;sound.play('footstep-'+(Math.floor(state.elapsed*3)%5+1),{volume:.5});}}}
   accumulator-=CONFIG.STEP;
  }
  if(!review){if(screen==='hud'&&!state.won&&!state.restoration&&clock>=animUntil)archive.animator.set(state.failure?'REALIGN_FAILURE':state.moving?'WALK':'IDLE');else if(screen==='title')archive.animator.set('TITLE_IDLE');}
  archive.update(state,(screen==='pause'||['how','settings','creation'].includes(screen))?0:dt*reviewSpeed,clock,{screen,reduced:settings.reduced,yaw:cameraYaw,pitch:cameraPitch,review,dragging:!!drag,validDrag:drag&&$('socket-target').classList.contains('valid')?drag.card:false});
  const segment=Math.floor(Math.max(0,state.bridge-.16)*13);if(segment>lastSegment&&screen==='hud')sound.play('bridge-segment',{volume:.55,rate:.94+segment*.012});lastSegment=segment;
  if(state.bridge>=1&&!bridgeComplete){bridgeComplete=true;sound.play('bridge-complete');}else if(state.bridge<1)bridgeComplete=false;
  const sec=sector(state),bHere=here(state,'brightness'),gHere=here(state,'gravity');
  $('failure').hidden=!state.failure||screen!=='hud';$('resets').textContent=String(state.resets).padStart(2,'0');$('fragments').innerHTML=state.fragments.length+' <small>/ '+TOTAL_FRAGMENTS+'</small>';card.classList.toggle('installed',state.installed);$('card-state').textContent=state.installed?'INSTALLED':selected==='brightness'?'SELECTED':'DRAG TO PLACE';
  gravityCard.hidden=!state.hasGravity;gravityCard.classList.toggle('installed',state.gInstalled);$('gravity-state').textContent=state.gInstalled?'INSTALLED':selected==='gravity'?'SELECTED':'DRAG TO PLACE';
  $('brightness-values').hidden=screen!=='hud'||!bHere;$('brightness-values').classList.toggle('far',!nearSocket(state,'brightness'));$('gravity-values').hidden=screen!=='hud'||!gHere;$('gravity-values').classList.toggle('far',!nearSocket(state,'gravity'));document.body.dataset.dual=String(!$('brightness-values').hidden&&!$('gravity-values').hidden);
  $('sector-label').textContent=sec===2?'SECTOR 02':'SECTOR 01';$('sector-name').textContent=sec===2?'Gravity Well':'Boot Atrium';$('socket-target').querySelector('small').textContent=drag?.card==='gravity'?'GRAVITY SOCKET':'BRIGHTNESS SOCKET';
  if(briefing){if(screen==='hud'){const t=state.elapsed-briefing.at;$(briefing.id).querySelectorAll('[data-line]').forEach(el=>el.classList.toggle('shown',t>Number(el.dataset.line)*2.4+.2));if(t>16||(briefing.id==='briefing'?state.installed:state.gInstalled))endBriefing();}}
  document.body.dataset.misstep=String(state.misstep>0&&state.misstep<.45);
  document.querySelectorAll('[data-level]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.level===state.brightness));});document.querySelectorAll('[data-gravity]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.gravity===state.gravity));});
  document.querySelectorAll('.progress li').forEach((el,i)=>{el.hidden=(i>=3?2:1)!==sec;el.classList.toggle('active',i===state.stage);el.classList.toggle('done',i<state.stage);});
  const puzzle=screen==='hud'&&(state.stage<3?bHere&&state.stage>0:gHere||(state.stage===5&&bHere))&&!state.failure&&!state.restoration&&!state.won;
  $('puzzle-panel').hidden=!puzzle;const typed=state.glyphInput.map(i=>SYMBOL[i]).concat(Array(3-state.glyphInput.length).fill('_')).join('  ');
  const pinned=state.pins.filter(Boolean).length;
  $('puzzle-label').textContent=state.stage===1?(state.readSolved?'Order restored: ◇  ○  △. The threshold is open.':state.brightness==='DIM'?'Plate order: ◇  →  ○  →  △':state.brightness==='RADIANT'?'Too bright. The plates are washed out.':state.glyphSeen?`Walk the plates in order: ${typed}${state.glyphInput.length?`   cooling in ${secs(TIMING.plateWindow-state.plateTimer)}s`:''}`:'Plates dark. DIM shows their order.')
   :state.stage===2?(state.cleared.length===3?'All fractures sealed. RADIANT restores the Kernel.':state.brightness==='DIM'?`${3-state.cleared.length} fracture${3-state.cleared.length===1?'':'s'} glowing on the floor.`:state.brightness==='RADIANT'?'Fractures are live. Do not touch them.':state.nodesSeen?`Sealed ${state.cleared.length} / 3. Walk into the rest.${state.cleared.length?` Hold: ${secs(TIMING.hold-state.holdTimer)}s`:''}`:'Fractures hidden. DIM shows them.')
   :state.stage===3?(state.gravity==='LOW'?`Slabs ${state.lift>=1?'up':'rising'}. LOW charge: ${secs(state.lowCharge)}s`:state.lift>0?'LOW spent. The slabs are sinking.':'Three slabs sunk in the pit. LOW lifts them.')
   :state.stage===4?(state.anchored?'Anchors hold. The stair is open.':state.gravity==='HEAVY'?`Anchors frozen. Pinned ${pinned} / 3. Deck crumbles in ${secs(TIMING.crumble*(1-state.crumble))}s`:`Anchors drifting. Pinned ${pinned} / 3.${state.crumble>0?' The deck is healing.':''}`)
   :(state.core>=1?'Core up. Step onto it.':state.locks.length===3?(state.brightness==='RADIANT'&&state.gravity==='LOW'?`Core rising. LOW charge: ${secs(state.lowCharge)}s`:'Locks set. RADIANT + LOW powers the core.'):state.locksSeen?`Locks ${state.locks.length} / 3. HEAVY to pin them.`:'Locks hidden. DIM + HEAVY shows them.');
  if(screen==='hud'){const k=(key,level)=>settings.touch?`tap ${level}`:`press ${key} for ${level}`,act=settings.touch?'ACT':'E';
   const objective=state.stage===0?(!state.installed?'Carry BRIGHTNESS to the glowing socket ahead.':state.brightness==='RADIANT'?(state.bridge<1?'The bridge is forming.':`Cross the bridge of light. ${secs(state.surge)}s of RADIANT left.`):`${k(3,'RADIANT')} to build the bridge.`)
    :state.stage===1?(!bHere?(state.installed?`Go to the gallery socket and press ${act} to bring BRIGHTNESS here.`:'Install BRIGHTNESS in the gallery socket.'):state.readSolved?'The way is open. Walk down to the Kernel.':!state.glyphSeen?`${k(1,'DIM')} to see the order of the floor plates.`:state.brightness==='DIM'?`Remember the order, then ${k(2,'BALANCED')} and walk it.`:state.brightness==='RADIANT'?`Too bright to read. ${k(2,'BALANCED')} first.`:`Walk the three plates in that order, without stopping. ${state.glyphInput.length} / 3`)
    :state.stage===2?(!bHere?(state.installed?`Go to the Kernel socket and press ${act} to bring BRIGHTNESS here.`:'Install BRIGHTNESS in the Kernel socket.'):state.cleared.length===3?`Back at the socket, ${k(3,'RADIANT')} to restore the Kernel.`:!state.nodesSeen?`${k(1,'DIM')} to find the fractures.`:state.brightness==='DIM'?`Remember where they are, then ${k(2,'BALANCED')} and walk into them.`:state.brightness==='RADIANT'?`Too bright. ${k(2,'BALANCED')} before touching a fracture.`:`Walk into the fractures to seal them. ${state.cleared.length} / 3`)
    :state.stage===3?(!gHere?(state.gInstalled?`Go to the violet socket and press ${act} to bring GRAVITY here.`:'Carry GRAVITY down the stair to the violet socket on the landing.'):state.lift>=1?`Cross the slabs before LOW spends. ${secs(state.lowCharge)}s`:state.gravity==='LOW'?'The slabs are rising.':`${k(4,'LOW')} to lift the sunken slabs.`)
    :state.stage===4?(!gHere?(state.gInstalled?`Go to the deck socket and press ${act} to bring GRAVITY here.`:'Install GRAVITY in the deck socket.'):state.anchored?'The anchors hold. Take the stair down to the core.':state.gravity==='HEAVY'?`Walk onto the frozen anchors. ${pinned} / 3, ${secs(TIMING.crumble*(1-state.crumble))}s before the deck crumbles.`:`${k(6,'HEAVY')} to freeze the drifting anchors.`)
    :(!bHere||!gHere?(!bHere&&!gHere?'Install BRIGHTNESS and GRAVITY in the two sockets ahead.':!bHere?'Install BRIGHTNESS in the cyan socket beside GRAVITY.':state.gInstalled?`Press ${act} at the violet socket to bring GRAVITY here.`:'Install GRAVITY in the violet socket beside BRIGHTNESS.'):state.core>=1?'Step onto the core.':state.locks.length===3?(state.brightness==='RADIANT'&&state.gravity==='LOW'?`Walk onto the core. ${secs(state.lowCharge)}s`:state.brightness!=='RADIANT'?`${k(3,'RADIANT')} to power the core.`:`${k(4,'LOW')} to raise it, then walk onto it.`):state.locksSeen?(state.gravity==='HEAVY'?`Walk onto the three locks. ${state.locks.length} / 3`:`${k(6,'HEAVY')} to pin the locks.`):state.brightness!=='DIM'?`${k(1,'DIM')} to find the core locks.`:`${k(6,'HEAVY')} with DIM to show the locks.`);
   $('objective').textContent=objective[0].toUpperCase()+objective.slice(1);
   const p=archive.socketScreen(drag?.card||'brightness');$('socket-target').hidden=true;$('socket-target').style.left=p.x+'px';$('socket-target').style.top=p.y+'px';
   const near=cardHere(),A=settings.touch?'ACT':'E';
   $('context').textContent=state.failure?'':near?(installedOf(near)?(here(state,near)?`${A} — take ${cardLabel(near)} back. ${near==='gravity'?'4 / 5 / 6 — change gravity':'1 / 2 / 3 — change the light'}`:`${A} — bring ${cardLabel(near)} to this socket`):(settings.touch?`Drag the ${cardLabel(near)} card into the socket, or press ACT`:`Drag the ${cardLabel(near)} card into the socket, or press E`)):state.stage===0&&!state.installed?(settings.touch?'Thumbstick to walk. The cyan glow ahead is the socket.':'WASD / arrows to walk. The cyan glow ahead is the socket.'):bHere&&state.stage<3?'Dim = see hidden. Balanced = touch. Radiant = build, but edges burn.':gHere&&state.stage<5?'Low = lift, but it spends. Normal = drift. Heavy = freeze, but the deck crumbles.':state.stage===1?'The gallery socket is on the right.':state.stage===2?'The Kernel socket is ahead on the left.':state.stage===3?'The violet socket is on the landing below.':state.stage===4?'The violet socket is on this deck, to the right.':'Two sockets ahead: cyan for BRIGHTNESS, violet for GRAVITY.';}

  if(now>toastUntil)$('toast').classList.remove('visible');if(!window.__READY__){window.__READY__=true;window.__READY_TIME__=performance.now();}requestAnimationFrame(frame);
 }requestAnimationFrame(frame);
 Object.defineProperty(window,'__GAME__',{get:()=>{const m=archive.metrics();return{pos:[state.x,state.z],fps:m.fps,draws:m.drawCalls,tris:m.triangles,speed:state.moving?speed(state):0};}});
 Object.defineProperty(window,'__CTRL__',{get:()=>({screen,state:JSON.parse(JSON.stringify(state)),settings:{...settings},audio:sound.status,metrics:archive.metrics(),socket:archive.socketScreen(),gravitySocket:archive.socketScreen('gravity'),startLatency,readyTime:window.__READY_TIME__,posterVisible:window.__POSTER_VISIBLE__,animation:archive.animator.state,video:{enabled:CONFIG.USE_TITLE_VIDEO,paused:$('title-video').paused,src:!!$('title-video').getAttribute('src')},ready:!!window.__READY__})});
 if(!review&&screen==='title')requestAnimationFrame(()=>requestAnimationFrame(startVideo));
}catch(error){$('boot-error').hidden=false;$('boot-error').textContent='The archive could not initialize graphics. Please enable hardware acceleration and reload.';console.error(error);}
