import {CONFIG} from './config.js';
import {createState,step,install,retrieve,nearSocket,restoreArchive,results,setBrightness,activateGlyph,clearNode} from './src/model.js';
import {ArchiveAudio} from './src/audio.js';
import {ANIMATIONS} from './src/animations.js';
import {initTutorial} from './src/tutorial.js';
const $=id=>document.getElementById(id);const reducedQuery=matchMedia('(prefers-reduced-motion: reduce)');
let manualTouch=false,videoEpoch=0;
let settings={master:80,music:65,effects:80,sensitivity:50,mute:false,reduced:reducedQuery.matches,touch:matchMedia('(pointer:coarse)').matches||innerWidth<700,invert:false};
try{const saved=JSON.parse(localStorage.getItem('ctrl-reality-settings')||'{}');manualTouch=!!saved.manualTouch;for(const k of Object.keys(settings))if((k!=='touch'||manualTouch)&&typeof saved[k]===typeof settings[k])settings[k]=typeof saved[k]==='number'?Math.max(0,Math.min(100,saved[k])):saved[k];}catch{}
initTutorial();
const sound=new ArchiveAudio();sound.apply(settings);let state=createState(),screen='title',returnScreen='title',archive,keys=new Set(),joystick={x:0,z:0},drag=null,selected=false,animUntil=0,toastUntil=0,startAt=0,startLatency=null,transitionUntil=0,cameraYaw=0,cameraPitch=0,footTimer=0,clock=0;
function applySettings(){document.body.classList.toggle('touch',settings.touch);sound.apply(settings);for(const [key,value]of Object.entries(settings)){const el=$(key);if(!el)continue;if(el.type==='checkbox')el.checked=value;else{el.value=value;document.querySelector(`output[for="${key}"]`).value=value+'%';}}if(settings.reduced)stopVideo();try{localStorage.setItem('ctrl-reality-settings',JSON.stringify({...settings,manualTouch}));}catch{}}
applySettings();
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');toastUntil=performance.now()+2600;}
function cancelInput(){sound.drag(false);keys.clear();joystick.x=joystick.z=0;$('stick').style.transform='';if(drag){drag=null;$('drag-card').hidden=true;}selected=false;}
let focusBefore=null;
function show(next,{focus=true}={}){const previous=screen;screen=next;toastUntil=0;$('toast').classList.remove('visible');document.body.dataset.screen=next;document.querySelectorAll('.screen').forEach(el=>el.hidden=el.id!==next);cancelInput();if(previous==='title'&&next!=='title')stopVideo();if(next==='title'){sound.stopShots();sound.setMode('title');startVideo();archive?.animator.set('TITLE_IDLE');}else if(next==='hud'){sound.setMode('game');if(previous==='pause')sound.play('pause-close',{bus:'UI_SFX'});}else if(next==='pause'){sound.setMode('pause');sound.play('pause-open',{bus:'UI_SFX'});}else if(next==='results'){sound.stopShots();sound.setMode('results');}
 if(focus&&next!=='hud')requestAnimationFrame(()=>$(next).querySelector('button,input')?.focus({preventScroll:true}));
}
function openPanel(name){sound.play('ui-open',{bus:'UI_SFX'});focusBefore=document.activeElement;returnScreen=screen;show(name);}
function back(){sound.play('ui-back',{bus:'UI_SFX'});sound.play('ui-close',{bus:'UI_SFX',volume:.35});const target=returnScreen;show(target);if(focusBefore?.isConnected)focusBefore.focus({preventScroll:true});}
function stopVideo(){videoEpoch++;const v=$('title-video');v.pause();v.removeAttribute('src');v.load();v.style.opacity='0';}
async function startVideo(){if(!CONFIG.USE_TITLE_VIDEO||innerWidth<=700||new URLSearchParams(location.search).has('gate')||settings.reduced||navigator.connection?.saveData||(navigator.deviceMemory&&navigator.deviceMemory<4)||screen!=='title')return;
 const v=$('title-video'),epoch=++videoEpoch;
 if(!v.getAttribute('src'))v.src=v.canPlayType('video/webm; codecs="vp9"')?'./media/title/title-desktop-loop.webm':'./media/title/title-desktop-loop.mp4';
 v.onloadeddata=()=>{if(screen==='title'&&epoch===videoEpoch)v.play().then(()=>{if(screen==='title'&&epoch===videoEpoch)v.style.opacity='1';}).catch(()=>{v.style.opacity='0';});};v.load();
}
const poster=$('poster');function markPoster(){if(poster.naturalWidth)window.__POSTER_VISIBLE__=performance.now();}if(poster.complete)markPoster();else poster.addEventListener('load',markPoster,{once:true});
$('title-video').addEventListener('error',()=>{$('title-video').style.opacity='0';});
function animate(name,duration=.8){archive?.animator.set(name);animUntil=clock+duration;}
let pendingStart=false,startRequestedAt=0;
function begin(){if(!archive)sound.mode='silent';sound.unlock();if(!pendingStart)startRequestedAt=performance.now();if(!archive){pendingStart=true;$('startb').setAttribute('aria-busy','true');$('startb').firstChild.textContent='Opening the archive ';return;}pendingStart=false;$('startb').removeAttribute('aria-busy');$('startb').firstChild.textContent='Enter the archive ';state=createState();document.body.dataset.restoring='false';$('hud').inert=false;$('restoration').hidden=true;archive.snapCamera();startAt=startRequestedAt;startLatency=null;show('hud',{focus:false});$('failure').hidden=true;animate('IDLE',0);transitionUntil=performance.now()+(settings.reduced?300:1000);$('transition').classList.add('active');setTimeout(()=>$('transition').classList.remove('active'),settings.reduced?40:110);toast('The archive has lost its light.');}
function changeBrightness(level){if(!setBrightness(state,level)){toast('Stand beside the installed control.');return;}sound.play('ui-tick',{bus:'UI_SFX'});if(state.stage===0&&level==='RADIANT'){sound.play('bridge-energy');animate('BRIDGE_REVEAL_REACTION',1.85);}if(restoreArchive(state))startRestoration();}
document.querySelectorAll('[data-level]').forEach(b=>b.addEventListener('click',()=>changeBrightness(b.dataset.level)));
document.querySelectorAll('[data-glyph]').forEach(b=>b.addEventListener('click',()=>{const ok=activateGlyph(state,Number(b.dataset.glyph));sound.play(ok?'socket-valid':'control-invalid');if(state.failure){animate('REALIGN_FAILURE',1.25);sound.play('failure-fracture');}if(state.readSolved){sound.play('checkpoint');toast('The archive remembers the sequence.');}}));
document.querySelectorAll('[data-node]').forEach(b=>b.addEventListener('click',()=>{if(clearNode(state,Number(b.dataset.node))){sound.play('control-socket');animate('CONTROL_DEPLOY');if(state.cleared.length===3)toast('Choose RADIANT. Restore the Kernel.');}}));
function pause(){if(screen!=='hud'||state.restoration||state.won)return;show('pause');}
function act(){if(screen!=='hud'||state.failure||state.won||state.restoration)return;sound.unlock();if(restoreArchive(state)){startRestoration();return;}if(nearSocket(state)){if(state.installed){retrieve(state);animate('CONTROL_RETRIEVE');sound.play('control-retrieve');toast('Brightness returned to your hand.');}else if(selected){installControl();}else{selected=true;animate('CONTROL_REACH');toast('Drag BRIGHTNESS to the socket. Or press E.');}}else if(restoreArchive(state)){startRestoration();}else toast('Move closer to an archive socket.');}
function installControl(){if(!install(state)){sound.play('control-invalid');toast('Bring Mara closer to the socket.');return false;}selected=false;animate('CONTROL_DEPLOY',1.2);sound.play('control-socket');setTimeout(()=>{if(screen==='hud'&&state.installed&&state.brightness==='RADIANT')sound.play('bridge-reveal');},350);toast('Choose RADIANT to restore the crossing.');return true;}
function startRestoration(){animate('VICTORY_IDLE',100);cancelInput();document.body.dataset.restoring='true';$('hud').inert=true;$('restoration').hidden=false;sound.play('victory');}
function win(){animate('VICTORY_IDLE',100);const r=results(state);$('result-time').textContent=Math.floor(r.seconds/60).toString().padStart(2,'0')+':'+(r.seconds%60).toString().padStart(2,'0');for(const k of ['resets','moves','rank'])$('result-'+k).textContent=r[k];$('result-fragments').textContent=r.fragments+' / 3';$('result-efficiency').textContent=r.efficiency+'%';setTimeout(()=>{if(state.won){$('restoration').hidden=true;show('results');}},1400);}
$('startb').addEventListener('click',begin);$('replay').addEventListener('click',begin);$('resume').addEventListener('click',()=>show('hud',{focus:false}));$('pause-button').addEventListener('click',pause);$('act').addEventListener('click',act);
$('restart').addEventListener('click',()=>{show('hud',{focus:false});state.failure=.001;sound.play('failure-fracture');animate('REALIGN_FAILURE',1.3);});
document.querySelectorAll('[data-open]').forEach(el=>el.addEventListener('click',()=>{sound.unlock();openPanel(el.dataset.open);}));document.querySelectorAll('.back').forEach(el=>el.addEventListener('click',back));document.querySelectorAll('.return-title').forEach(el=>el.addEventListener('click',()=>{state=createState();document.body.dataset.restoring='false';$('hud').inert=false;$('restoration').hidden=true;$('failure').hidden=true;show('title');}));
document.querySelectorAll('button').forEach(b=>{b.addEventListener('pointerenter',()=>sound.play('ui-hover',{bus:'UI_SFX',volume:.35}));b.addEventListener('click',()=>{sound.unlock();sound.play('ui-confirm',{bus:'UI_SFX'});});});
for(const k of Object.keys(settings))$(k)?.addEventListener('input',e=>{if(k==='touch')manualTouch=true;settings[k]=e.target.type==='checkbox'?e.target.checked:Number(e.target.value);applySettings();sound.unlock();sound.play(e.target.type==='checkbox'?'ui-toggle':'ui-tick',{bus:'UI_SFX',volume:.5});});
reducedQuery.addEventListener('change',e=>{settings.reduced=e.matches;applySettings();});
window.addEventListener('keydown',e=>{const key=e.key.toLowerCase();if(key==='tab'&&screen!=='hud'){const controls=[...$(screen).querySelectorAll('button:not(:disabled),input')];const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}return;}
 if(key==='escape'){e.preventDefault();if(screen==='hud')pause();else if(screen==='pause')show('hud',{focus:false});else if(['settings','how','creation'].includes(screen))back();return;}
 if(screen!=='hud'||e.repeat)return;if(['1','2','3'].includes(key)){changeBrightness(['DIM','BALANCED','RADIANT'][Number(key)-1]);return;}if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(key))e.preventDefault();if(key==='e'){act();return;}keys.add(key);});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
window.addEventListener('blur',()=>{cancelInput();if(screen==='hud')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelInput();if(screen==='hud')pause();sound.context?.suspend();stopVideo();}else if(screen==='title')startVideo();});
$('world').addEventListener('pointermove',e=>{if(screen!=='hud'||e.pointerType==='touch'||!e.buttons)return;cameraYaw=Math.max(-.38,Math.min(.38,cameraYaw-e.movementX*.0015*settings.sensitivity/50));cameraPitch=Math.max(-.5,Math.min(.5,cameraPitch+e.movementY*.001*(settings.invert?-1:1)));});
const joy=$('joystick');let joyId=null;function moveJoy(e){const r=joy.getBoundingClientRect();const dx=e.clientX-(r.x+r.width/2),dy=e.clientY-(r.y+r.height/2),l=Math.hypot(dx,dy),scale=Math.min(1,38/(l||1));joystick.x=dx*scale/38;joystick.z=dy*scale/38;$('stick').style.transform=`translate(${dx*scale}px,${dy*scale}px)`;}
joy.addEventListener('pointerdown',e=>{if(screen!=='hud')return;joyId=e.pointerId;joy.setPointerCapture(joyId);moveJoy(e);sound.unlock();});joy.addEventListener('pointermove',e=>{if(e.pointerId===joyId)moveJoy(e);});for(const event of ['pointerup','pointercancel','lostpointercapture'])joy.addEventListener(event,()=>{joyId=null;joystick.x=joystick.z=0;$('stick').style.transform='';});
const card=$('brightness');card.addEventListener('pointerdown',e=>{if(screen!=='hud'||state.failure)return;sound.unlock();if(state.installed){toast('Return to the socket and press ACT to retrieve.');return;}drag={id:e.pointerId,x:e.clientX,y:e.clientY,moved:false};card.setPointerCapture(e.pointerId);selected=true;animate('CONTROL_PULL');sound.play('control-pickup');sound.drag(true);});
card.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>8)drag.moved=true;if(drag.moved){$('drag-card').hidden=false;$('drag-card').style.left=e.clientX+'px';$('drag-card').style.top=e.clientY+'px';animate('CONTROL_DRAG',.1);const p=archive.socketScreen();const valid=nearSocket(state)&&Math.hypot(e.clientX-p.x,e.clientY-p.y)<85;if(valid&&!$('socket-target').classList.contains('valid'))sound.play('socket-valid');$('socket-target').classList.toggle('valid',valid);}});
card.addEventListener('pointerup',e=>{if(!drag)return;const d=drag;sound.drag(false);drag=null;$('drag-card').hidden=true;$('socket-target').classList.remove('valid');if(d.moved){const p=archive.socketScreen();if(Math.hypot(e.clientX-p.x,e.clientY-p.y)<85&&nearSocket(state))installControl();else{sound.play('control-invalid');toast(nearSocket(state)?'Release over the glowing socket.':'Bring Mara closer to the socket.');animate('IDLE');}}else{selected=true;toast('BRIGHTNESS selected. Press E or ACT near the socket.');}});card.addEventListener('pointercancel',()=>{sound.drag(false);drag=null;selected=false;$('drag-card').hidden=true;});card.addEventListener('click',e=>{if(e.detail===0&&!state.installed){selected=true;toast('BRIGHTNESS selected. Press E or ACT near the socket.');}});
window.addEventListener('resize',()=>{archive?.resize();cancelInput();if(!manualTouch){settings.touch=matchMedia('(pointer:coarse)').matches||innerWidth<700;applySettings();}});window.addEventListener('pagehide',()=>sound.teardown());
let review=null,reviewState='IDLE',reviewSpeed=1;if(new URLSearchParams(location.search).has('review')){review='front';const el=document.createElement('div');el.className='review-controls';el.innerHTML='<label>Animation <select id="review-state">'+ANIMATIONS.map(a=>`<option>${a}</option>`).join('')+'</select></label><label>View <select id="review-view"><option value="front">Front</option><option value="side">Side</option><option value="rear">Rear three-quarter</option></select></label><label>Speed <select id="review-speed"><option value="1">1×</option><option value="0.5">½×</option></select></label>';$('interface').append(el);$('review-state').onchange=e=>{reviewState=e.target.value;archive.animator.set(reviewState);};$('review-view').onchange=e=>review=e.target.value;$('review-speed').onchange=e=>reviewSpeed=Number(e.target.value);}
window.__INTERFACE_READY__=true;
show('title',{focus:false});
try{const {createArchive}=await import('./src/scene.js');archive=await createArchive($('world'));if(pendingStart)begin();if(review){document.querySelectorAll('.screen').forEach(el=>el.hidden=true);$('title-media').style.display='none';stopVideo();archive.animator.set(reviewState);}
 let previous=performance.now(),accumulator=0,bridgeComplete=false,lastSegment=0;function frame(now){const dt=Math.min(.05,(now-previous)/1000);previous=now;clock+=dt;accumulator+=dt;
  while(accumulator>=CONFIG.STEP){if(screen==='hud'&&!review){const input={x:(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0)+joystick.x,z:(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0)+joystick.z};if(drag)input.x=input.z=0;const events=step(state,input,CONFIG.STEP);for(const event of events){if(event==='victory'){win();}if(event==='failure'){animate('REALIGN_FAILURE',1.3);sound.stopShots();sound.play('failure-fracture');setTimeout(()=>{if(state.failure)sound.play('failure-reverse');},180);}if(event==='reset'){sound.play('checkpoint');toast('Reality realigned.');}if(event==='fragment'){sound.play('fragment');toast('A memory recovered.');}if(event==='checkpoint'){animate('CHECKPOINT');sound.play('checkpoint');toast('Checkpoint restored.');}}
   if(startLatency===null)startLatency=performance.now()-startAt;if(state.moving&&!state.failure){footTimer+=CONFIG.STEP;if(footTimer>.4){footTimer=0;sound.play('footstep-'+(Math.floor(state.elapsed*3)%5+1),{volume:.5});}}}
   accumulator-=CONFIG.STEP;
  }
  if(!review){if(screen==='hud'&&!state.won&&!state.restoration&&clock>=animUntil)archive.animator.set(state.failure?'REALIGN_FAILURE':state.moving?'WALK':'IDLE');else if(screen==='title')archive.animator.set('TITLE_IDLE');}
  archive.update(state,(screen==='pause'||['how','settings','creation'].includes(screen))?0:dt*reviewSpeed,clock,{screen,reduced:settings.reduced,yaw:cameraYaw,pitch:cameraPitch,review,dragging:!!drag,validDrag:$('socket-target').classList.contains('valid')});
  const segment=Math.floor(Math.max(0,state.bridge-.16)*13);if(segment>lastSegment&&screen==='hud')sound.play('bridge-segment',{volume:.55,rate:.94+segment*.012});lastSegment=segment;
  if(state.bridge>=1&&!bridgeComplete){bridgeComplete=true;sound.play('bridge-complete');}else if(state.bridge<1)bridgeComplete=false;
  $('failure').hidden=!state.failure||screen!=='hud';$('resets').textContent=String(state.resets).padStart(2,'0');$('fragments').innerHTML=state.fragments.length+' <small>/ 3</small>';card.classList.toggle('installed',state.installed);$('card-state').textContent=state.installed?'INSTALLED':selected?'SELECTED':'DRAG TO PLACE';
  $('brightness-values').hidden=screen!=='hud'||!state.installed||state.installedSocket!==state.stage;
  document.querySelectorAll('[data-level]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.level===state.brightness));});
  document.querySelectorAll('.progress li').forEach((el,i)=>{el.classList.toggle('active',i===state.stage);el.classList.toggle('done',i<state.stage);});
  const puzzle=screen==='hud'&&nearSocket(state)&&state.installed&&state.installedSocket===state.stage&&state.stage>0&&!state.failure&&!state.restoration&&!state.won;
  $('puzzle-panel').hidden=!puzzle;$('glyph-controls').hidden=state.stage!==1||state.brightness!=='BALANCED'||!state.glyphSeen||state.readSolved;$('node-controls').hidden=state.stage!==2||state.brightness!=='BALANCED'||!state.nodesSeen;
  $('puzzle-label').textContent=state.stage===1?(state.readSolved?'Sequence restored. Cross the threshold.':state.brightness==='DIM'?'Remember: ◇  →  ○  →  △':state.brightness==='RADIANT'?'Too bright. The inscription disappears.':state.glyphSeen?`Repeat the sequence. ${state.glyphInput.length} / 3`:'DIM reveals what the archive remembers.'):(state.cleared.length===3?'All seals restored. Choose RADIANT.':state.brightness==='DIM'?'Three fractures revealed: I · II · III':state.brightness==='RADIANT'?'Corruption is active. Lower the light.':state.nodesSeen?'Seal the three remembered fractures.':'DIM reveals the hidden fractures.');
  document.querySelectorAll('[data-node]').forEach(b=>{b.disabled=state.cleared.includes(Number(b.dataset.node));});
  if(screen==='hud'){$('objective').textContent=state.stage===0?(state.installed?(state.brightness==='RADIANT'?'Cross the restored bridge.':'Choose RADIANT. Reveal the bridge.'):'Bring BRIGHTNESS to the socket.'):state.stage===1?(state.readSolved?'Cross the open threshold.':'Read the hidden archive sequence.'):'Clear the fractures. Restore the Kernel.';const near=nearSocket(state),p=archive.socketScreen();$('socket-target').hidden=true;$('socket-target').style.left=p.x+'px';$('socket-target').style.top=p.y+'px';$('context').textContent=state.failure?'':near?(state.installed?(state.installedSocket!==state.stage?'E / ACT — recall BRIGHTNESS through the relay.':'E / ACT — retrieve BRIGHTNESS'):'Drag BRIGHTNESS into the glowing socket'):(state.stage===0?(settings.touch?'Use the thumbstick. Approach the cyan socket.':'WASD / arrows — approach the cyan socket.'):'Follow the bronze channel.');}

  if(now>toastUntil)$('toast').classList.remove('visible');if(!window.__READY__){window.__READY__=true;window.__READY_TIME__=performance.now();}requestAnimationFrame(frame);
 }requestAnimationFrame(frame);
 Object.defineProperty(window,'__GAME__',{get:()=>{const m=archive.metrics();return{pos:[state.x,state.z],fps:m.fps,draws:m.drawCalls,tris:m.triangles,speed:state.moving?3.4:0};}});
 Object.defineProperty(window,'__CTRL__',{get:()=>({screen,state:JSON.parse(JSON.stringify(state)),settings:{...settings},audio:sound.status,metrics:archive.metrics(),socket:archive.socketScreen(),startLatency,readyTime:window.__READY_TIME__,posterVisible:window.__POSTER_VISIBLE__,animation:archive.animator.state,video:{enabled:CONFIG.USE_TITLE_VIDEO,paused:$('title-video').paused,src:!!$('title-video').getAttribute('src')},ready:!!window.__READY__})});
 if(!review&&screen==='title')requestAnimationFrame(()=>requestAnimationFrame(startVideo));
}catch(error){$('boot-error').hidden=false;$('boot-error').textContent='The archive could not initialize graphics. Please enable hardware acceleration and reload.';console.error(error);}
