import {CONFIG} from './config.js';
import {createState,step,install,retrieve,nearSocket,restoreArchive,results} from './src/model.js';
import {createArchive} from './src/scene.js';
import {ArchiveAudio} from './src/audio.js';
import {ANIMATIONS} from './assets/mara.js';
const $=id=>document.getElementById(id);const reducedQuery=matchMedia('(prefers-reduced-motion: reduce)');
let manualTouch=false;
let settings={master:80,music:65,effects:80,sensitivity:50,mute:false,reduced:reducedQuery.matches,touch:matchMedia('(pointer:coarse)').matches||innerWidth<700,invert:false};
try{const saved=JSON.parse(localStorage.getItem('ctrl-reality-settings')||'{}');manualTouch=!!saved.manualTouch;for(const k of Object.keys(settings))if((k!=='touch'||manualTouch)&&typeof saved[k]===typeof settings[k])settings[k]=typeof saved[k]==='number'?Math.max(0,Math.min(100,saved[k])):saved[k];}catch{}
const sound=new ArchiveAudio();sound.apply(settings);let state=createState(),screen='title',returnScreen='title',archive,keys=new Set(),joystick={x:0,z:0},drag=null,selected=false,animUntil=0,toastUntil=0,startAt=0,startLatency=null,transitionUntil=0,cameraYaw=0,cameraPitch=0,footTimer=0,clock=0;
function applySettings(){document.body.classList.toggle('touch',settings.touch);sound.apply(settings);for(const [key,value]of Object.entries(settings)){const el=$(key);if(!el)continue;if(el.type==='checkbox')el.checked=value;else{el.value=value;document.querySelector(`output[for="${key}"]`).value=value+'%';}}if(settings.reduced)stopVideo();try{localStorage.setItem('ctrl-reality-settings',JSON.stringify({...settings,manualTouch}));}catch{}}
applySettings();
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');toastUntil=performance.now()+2600;}
function cancelInput(){sound.drag(false);keys.clear();joystick.x=joystick.z=0;$('stick').style.transform='';if(drag){drag=null;$('drag-card').hidden=true;}selected=false;}
let focusBefore=null;
function show(next,{focus=true}={}){const previous=screen;screen=next;toastUntil=0;$('toast').classList.remove('visible');document.body.dataset.screen=next;document.querySelectorAll('.screen').forEach(el=>el.hidden=el.id!==next);cancelInput();if(previous==='title'&&next!=='title')stopVideo();if(next==='title'){sound.stopShots();sound.setMode('title');startVideo();archive?.animator.set('TITLE_IDLE');}else if(next==='hud'){sound.setMode('game');if(previous==='pause')sound.play('pause-close',{bus:'UI_SFX'});}else if(next==='pause'){sound.setMode('pause');sound.play('pause-open',{bus:'UI_SFX'});}else if(next==='results'){sound.stopShots();sound.setMode('results');}
 if(focus&&next!=='hud')requestAnimationFrame(()=>$(next).querySelector('button,input')?.focus({preventScroll:true}));
}
function openPanel(name){focusBefore=document.activeElement;returnScreen=screen;show(name);}
function back(){const target=returnScreen;show(target);if(focusBefore?.isConnected)focusBefore.focus({preventScroll:true});}
function stopVideo(){const v=$('title-video');v.pause();v.removeAttribute('src');v.load();v.style.opacity='0';}
async function startVideo(){if(!CONFIG.USE_TITLE_VIDEO||settings.reduced||navigator.connection?.saveData||(navigator.deviceMemory&&navigator.deviceMemory<4)||screen!=='title')return;const v=$('title-video');if(!v.getAttribute('src'))v.src=CONFIG.TITLE_VIDEO;try{await v.play();if(screen==='title')v.style.opacity='1';else stopVideo();}catch{v.style.opacity='0';}}
if(CONFIG.POSTER_AVAILABLE){$('poster').src=CONFIG.TITLE_POSTER;$('poster').hidden=false;$('poster').addEventListener('error',()=>{$('poster').hidden=true;});}
$('title-video').addEventListener('error',()=>{$('title-video').style.opacity='0';});
function animate(name,duration=.8){archive.animator.set(name);animUntil=clock+duration;}
function begin(){sound.unlock();state=createState();archive.snapCamera();startAt=performance.now();startLatency=null;show('hud',{focus:false});$('failure').hidden=true;animate('ENTER_ARCHIVE',settings.reduced?0:1.05);transitionUntil=performance.now()+(settings.reduced?300:1000);$('transition').classList.add('active');setTimeout(()=>$('transition').classList.remove('active'),settings.reduced?40:110);toast('The archive has lost its light.');}
function pause(){if(screen!=='hud')return;show('pause');}
function act(){if(screen!=='hud'||state.failure||state.won)return;sound.unlock();if(nearSocket(state)){if(state.installed){retrieve(state);animate('CONTROL_RETRIEVE');sound.play('control-retrieve');toast('Brightness returned to your hand.');}else if(selected){installControl();}else{selected=true;animate('CONTROL_REACH');toast('Drag BRIGHTNESS to the socket. Or press E.');}}else if(restoreArchive(state)){win();}else toast('Move closer to an archive socket.');}
function installControl(){if(!install(state)){sound.play('control-invalid');toast('Bring Mara closer to the socket.');return false;}selected=false;animate('CONTROL_DEPLOY',1.2);sound.play('control-socket');setTimeout(()=>{if(screen==='hud'&&state.installed)sound.play('bridge-reveal');},350);toast('A forgotten path returns.');return true;}
function win(){animate('VICTORY_IDLE',100);sound.play('victory');const r=results(state);$('result-time').textContent=Math.floor(r.seconds/60).toString().padStart(2,'0')+':'+(r.seconds%60).toString().padStart(2,'0');for(const k of ['resets','moves','rank'])$('result-'+k).textContent=r[k];$('result-fragments').textContent=r.fragments+' / 3';$('result-efficiency').textContent=r.efficiency+'%';setTimeout(()=>{if(state.won){show('results');sound.play('victory');}},900);}
$('startb').addEventListener('click',begin);$('replay').addEventListener('click',begin);$('resume').addEventListener('click',()=>show('hud',{focus:false}));$('pause-button').addEventListener('click',pause);$('act').addEventListener('click',act);
$('restart').addEventListener('click',()=>{show('hud',{focus:false});state.failure=.001;sound.play('failure-fracture');animate('REALIGN_FAILURE',1.3);});
document.querySelectorAll('[data-open]').forEach(el=>el.addEventListener('click',()=>{sound.unlock();openPanel(el.dataset.open);}));document.querySelectorAll('.back').forEach(el=>el.addEventListener('click',back));document.querySelectorAll('.return-title').forEach(el=>el.addEventListener('click',()=>{state=createState();$('failure').hidden=true;show('title');}));
document.querySelectorAll('button').forEach(b=>{b.addEventListener('pointerenter',()=>sound.play('ui-hover',{bus:'UI_SFX',volume:.35}));b.addEventListener('click',()=>{sound.unlock();sound.play('ui-confirm',{bus:'UI_SFX'});});});
for(const k of Object.keys(settings))$(k)?.addEventListener('input',e=>{if(k==='touch')manualTouch=true;settings[k]=e.target.type==='checkbox'?e.target.checked:Number(e.target.value);applySettings();sound.unlock();sound.play('ui-tick',{bus:'UI_SFX',volume:.5});});
reducedQuery.addEventListener('change',e=>{settings.reduced=e.matches;applySettings();});
window.addEventListener('keydown',e=>{const key=e.key.toLowerCase();if(key==='tab'&&screen!=='hud'){const controls=[...$(screen).querySelectorAll('button:not(:disabled),input')];const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}return;}
 if(key==='escape'){e.preventDefault();if(screen==='hud')pause();else if(screen==='pause')show('hud',{focus:false});else if(['settings','how','creation'].includes(screen))back();return;}
 if(screen!=='hud'||e.repeat)return;if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(key))e.preventDefault();if(key==='e'){act();return;}keys.add(key);});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
window.addEventListener('blur',()=>{cancelInput();if(screen==='hud')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelInput();if(screen==='hud')pause();sound.context?.suspend();stopVideo();}else if(screen==='title')startVideo();});
$('world').addEventListener('pointermove',e=>{if(screen!=='hud'||e.pointerType==='touch'||!e.buttons)return;cameraYaw=Math.max(-.38,Math.min(.38,cameraYaw-e.movementX*.0015*settings.sensitivity/50));cameraPitch=Math.max(-.5,Math.min(.5,cameraPitch+e.movementY*.001*(settings.invert?-1:1)));});
const joy=$('joystick');let joyId=null;function moveJoy(e){const r=joy.getBoundingClientRect();const dx=e.clientX-(r.x+r.width/2),dy=e.clientY-(r.y+r.height/2),l=Math.hypot(dx,dy),scale=Math.min(1,38/(l||1));joystick.x=dx*scale/38;joystick.z=dy*scale/38;$('stick').style.transform=`translate(${dx*scale}px,${dy*scale}px)`;}
joy.addEventListener('pointerdown',e=>{if(screen!=='hud')return;joyId=e.pointerId;joy.setPointerCapture(joyId);moveJoy(e);sound.unlock();});joy.addEventListener('pointermove',e=>{if(e.pointerId===joyId)moveJoy(e);});for(const event of ['pointerup','pointercancel','lostpointercapture'])joy.addEventListener(event,()=>{joyId=null;joystick.x=joystick.z=0;$('stick').style.transform='';});
const card=$('brightness');card.addEventListener('pointerdown',e=>{if(screen!=='hud'||state.failure)return;sound.unlock();if(state.installed){toast('Return to the socket and press ACT to retrieve.');return;}drag={id:e.pointerId,x:e.clientX,y:e.clientY,moved:false};card.setPointerCapture(e.pointerId);selected=true;animate('CONTROL_PULL');sound.play('control-pickup');sound.drag(true);});
card.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>8)drag.moved=true;if(drag.moved){$('drag-card').hidden=false;$('drag-card').style.left=e.clientX+'px';$('drag-card').style.top=e.clientY+'px';animate('CONTROL_DRAG',.1);const p=archive.socketScreen();const valid=nearSocket(state)&&Math.hypot(e.clientX-p.x,e.clientY-p.y)<85;if(valid&&!$('socket-target').classList.contains('valid'))sound.play('socket-valid');$('socket-target').classList.toggle('valid',valid);}});
card.addEventListener('pointerup',e=>{if(!drag)return;const d=drag;sound.drag(false);drag=null;$('drag-card').hidden=true;$('socket-target').classList.remove('valid');if(d.moved){const p=archive.socketScreen();if(Math.hypot(e.clientX-p.x,e.clientY-p.y)<85&&nearSocket(state))installControl();else{sound.play('control-invalid');toast(nearSocket(state)?'Release over the glowing socket.':'Bring Mara closer to the socket.');animate('IDLE');}}else{selected=true;toast('BRIGHTNESS selected. Press E or ACT near the socket.');}});card.addEventListener('pointercancel',()=>{sound.drag(false);drag=null;selected=false;$('drag-card').hidden=true;});card.addEventListener('click',e=>{if(e.detail===0&&!state.installed){selected=true;toast('BRIGHTNESS selected. Press E or ACT near the socket.');}});
window.addEventListener('resize',()=>{archive?.resize();cancelInput();if(!manualTouch){settings.touch=matchMedia('(pointer:coarse)').matches||innerWidth<700;applySettings();}});window.addEventListener('pagehide',()=>sound.teardown());
let review=null,reviewState='IDLE',reviewSpeed=1;if(new URLSearchParams(location.search).has('review')){review='front';const el=document.createElement('div');el.className='review-controls';el.innerHTML='<label>Animation <select id="review-state">'+ANIMATIONS.map(a=>`<option>${a}</option>`).join('')+'</select></label><label>View <select id="review-view"><option value="front">Front</option><option value="side">Side</option><option value="rear">Rear three-quarter</option></select></label><label>Speed <select id="review-speed"><option value="1">1×</option><option value="0.5">½×</option></select></label>';$('interface').append(el);$('review-state').onchange=e=>{reviewState=e.target.value;archive.animator.set(reviewState);};$('review-view').onchange=e=>review=e.target.value;$('review-speed').onchange=e=>reviewSpeed=Number(e.target.value);}
try{archive=await createArchive($('world'));show('title',{focus:false});if(review){document.querySelectorAll('.screen').forEach(el=>el.hidden=true);$('title-media').style.display='none';stopVideo();archive.animator.set(reviewState);}
 let previous=performance.now(),accumulator=0,bridgeComplete=false;function frame(now){const dt=Math.min(.05,(now-previous)/1000);previous=now;clock+=dt;accumulator+=dt;
  while(accumulator>=CONFIG.STEP){if(screen==='hud'&&!review){const input={x:(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0)+joystick.x,z:(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0)+joystick.z};if(drag)input.x=input.z=0;const events=step(state,input,CONFIG.STEP);for(const event of events){if(event==='failure'){animate('REALIGN_FAILURE',1.3);sound.stopShots();sound.play('failure-fracture');setTimeout(()=>{if(state.failure)sound.play('failure-reverse');},180);}if(event==='reset'){sound.play('checkpoint');toast('Reality realigned.');}if(event==='fragment'){sound.play('fragment');toast('A memory recovered.');}if(event==='checkpoint'){animate('CHECKPOINT');sound.play('checkpoint');toast('Checkpoint restored.');}}
   if(startLatency===null)startLatency=performance.now()-startAt;if(state.moving&&!state.failure){footTimer+=CONFIG.STEP;if(footTimer>.4){footTimer=0;sound.play('footstep-'+(Math.floor(state.elapsed*3)%5+1),{volume:.5});}}}
   accumulator-=CONFIG.STEP;
  }
  if(!review){if(screen==='hud'&&clock>=animUntil)archive.animator.set(state.failure?'REALIGN_FAILURE':state.moving?'WALK':'IDLE');else if(screen==='title')archive.animator.set('TITLE_IDLE');}
  archive.update(state,(screen==='pause'||['how','settings','creation'].includes(screen))?0:dt*reviewSpeed,clock,{screen,reduced:settings.reduced,yaw:cameraYaw,pitch:cameraPitch,review,dragging:!!drag,validDrag:$('socket-target').classList.contains('valid')});
  if(state.bridge>=1&&!bridgeComplete){bridgeComplete=true;sound.play('bridge-complete');}else if(state.bridge<1)bridgeComplete=false;
  $('failure').hidden=!state.failure||screen!=='hud';$('resets').textContent=String(state.resets).padStart(2,'0');$('fragments').innerHTML=state.fragments.length+' <small>/ 3</small>';card.classList.toggle('installed',state.installed);$('card-state').textContent=state.installed?'INSTALLED':selected?'SELECTED':'DRAG TO PLACE';
  if(screen==='hud'){$('objective').textContent=state.checkpointReached?'Restore the Atrium core.':state.installed?'Cross the restored bridge.':'Bring BRIGHTNESS to the socket.';const near=nearSocket(state),p=archive.socketScreen();$('socket-target').hidden=true;$('socket-target').style.left=p.x+'px';$('socket-target').style.top=p.y+'px';$('context').textContent=state.failure?'':Math.hypot(state.x,state.z+17)<2.3?'Restore the Atrium':near?(state.installed?'Retrieve Brightness':'Drag BRIGHTNESS into the glowing socket'):(state.z>1?'Move toward the cyan socket.':'');}
  if(now>toastUntil)$('toast').classList.remove('visible');window.__READY__=true;requestAnimationFrame(frame);
 }requestAnimationFrame(frame);
 Object.defineProperty(window,'__CTRL__',{get:()=>({screen,state:JSON.parse(JSON.stringify(state)),settings:{...settings},audio:sound.status,metrics:archive.metrics(),socket:archive.socketScreen(),startLatency,animation:archive.animator.state,video:{enabled:CONFIG.USE_TITLE_VIDEO,paused:$('title-video').paused,src:!!$('title-video').getAttribute('src')},ready:!!window.__READY__})});
 setTimeout(()=>{if(!review)startVideo();},300);
}catch(error){$('boot-error').hidden=false;$('boot-error').textContent='The archive could not initialize graphics. Please enable hardware acceleration and reload.';console.error(error);}
