// Real gameplay captures, loaded only when the handbook is opened.
export function initTutorial(){
 const $=id=>document.getElementById(id),panel=$('how');let index=0,startX=0;
 const steps=[['CARRY','Take the <br>light.','The archive is dark. You hold its last light as the BRIGHTNESS card at the bottom of the screen. Walk to a glowing socket and drag the card into it.','Move: WASD, arrows or the thumbstick. Install: drag the card, or stand at the socket and press E.','pull'],['CHOOSE','Set how <br>bright.','Once the card is in a socket, pick a light with 1, 2 or 3. DIM shows hidden plates and fractures. BALANCED lets Mara touch them. RADIANT builds the bridge, but the far edges burn.','You must stand at the socket to change the light. Press E there to take the card back.','install'],['RESTORE','Walk it <br>back to life.','Build the bridge with RADIANT and cross. In the gallery, DIM shows the order of three floor plates; walk them in that order under BALANCED. At the Kernel, seal the fractures by walking into them, then RADIANT.','A wrong plate only resets the order. Falling or touching a live fracture sends you back to the last checkpoint. RADIANT fades after eight seconds, plates cool between steps and fractures reopen if you seal too slowly.','restore'],['WEIGH','Carry the <br>weight.','The restored Kernel hands you a second card: GRAVITY. It fits only the violet sockets of the Well below. LOW (4) lifts sunken slabs but spends in nine seconds. HEAVY (6) freezes the drifting anchors, but the deck crumbles while it holds. NORMAL (5) lets go.','At the core, both cards sit side by side. DIM plus HEAVY shows the locks. RADIANT plus LOW raises the core. Step onto it to finish.','install']];
 function show(n){index=(n+4)%4;const s=steps[index];$('lesson-kicker').textContent=`0${index+1} / ${s[0]}`;$('how-heading').innerHTML=s[1];$('lesson-copy').textContent=s[2];$('lesson-hint').textContent=s[3];$('lesson-progress').textContent=`0${index+1} / 04`;$('lesson-image').src=`./media/tutorial/${s[4]}.webp`;$('lesson-image').alt=s[0]==='CARRY'?'Mara holding the detached Brightness card':s[0]==='CHOOSE'?'Brightness locks into the physical socket':s[0]==='WEIGH'?'A control card locking into a socket; the Gravity card installs the same way':'Individual bridge segments assemble toward the destination';panel.querySelectorAll('.tutorial-pagination i').forEach((e,i)=>e.classList.toggle('active',i===index));}
 $('lesson-prev').onclick=()=>show(index-1);$('lesson-next').onclick=()=>show(index+1);
 document.querySelectorAll('[data-open="how"]').forEach(b=>b.addEventListener('click',()=>show(0)));
 document.addEventListener('keydown',e=>{if(panel.hidden)return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();show(index+(e.key==='ArrowRight'?1:-1));}});
 panel.addEventListener('pointerdown',e=>{startX=e.clientX;});panel.addEventListener('pointerup',e=>{if(Math.abs(e.clientX-startX)>60)show(index+(e.clientX<startX?1:-1));});
}
