// Reproducible subset of pinned Three.js r180; original vendor sources stay intact.
import fs from 'node:fs/promises';import path from 'node:path';import {build}from'esbuild';
async function sources(dir){const out=[];for(const e of await fs.readdir(dir,{withFileTypes:true})){if(e.name==='vendor')continue;const p=path.join(dir,e.name);if(e.isDirectory())out.push(...await sources(p));else if(e.name.endsWith('.js'))out.push(p);}return out;}
const names=new Set(['BufferAttribute','BufferGeometry','Float32BufferAttribute','InstancedBufferAttribute','InterleavedBuffer','InterleavedBufferAttribute','TriangleFanDrawMode','TriangleStripDrawMode','TrianglesDrawMode','Vector3']);
for(const file of await sources('game')){const text=await fs.readFile(file,'utf8');for(const match of text.matchAll(/THREE\.([A-Za-z][A-Za-z0-9_]*)/g))names.add(match[1]);}
const entry=`export {${[...names].sort().join(',')}} from 'three';`;
await build({stdin:{contents:entry,resolveDir:process.cwd(),sourcefile:'archive-three-entry.js'},bundle:true,minify:true,format:'esm',platform:'browser',target:'es2022',legalComments:'eof',outfile:'game/vendor/archive-three.js',banner:{js:'// Generated by scripts/build-three.mjs from three@0.180.0. MIT license retained below.'}});
const utility='game/vendor/BufferGeometryUtils.js';const text=await fs.readFile(utility,'utf8');await fs.writeFile(utility,text.replace("from './three.module.js'","from './archive-three.js'"));
console.log('Built local Three.js subset:',names.size,'exports,',(await fs.stat('game/vendor/archive-three.js')).size,'bytes');
