import puppeteer from 'puppeteer';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const dir='production/gate-runs/boot-atrium';await fs.mkdir(dir,{recursive:true});const browser=await puppeteer.launch({headless:true,args:['--enable-unsafe-swiftshader','--disable-background-timer-throttling','--disable-renderer-backgrounding']});const report={date:new Date().toISOString(),checks:[],errors:[],devices:[]};const check=(name,value)=>{assert.ok(value,name);report.checks.push(name);console.log('PASS',name);};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));const snap=p=>p.evaluate(()=>window.__CTRL__);
async function shot(p,name){await p.screenshot({path:`${dir}/${name}.png`});}
async function move(p,x,z){for(const [axis,target,positive,negative]of [['x',x,'d','a'],['z',z,'s','w']]){let s=await snap(p);const delta=target-s.state[axis];if(Math.abs(delta)<.12)continue;const key=delta>0?positive:negative;await p.keyboard.down(key);await p.waitForFunction((axis,target,dir)=>dir>0?window.__CTRL__.state[axis]>=target-.09:window.__CTRL__.state[axis]<=target+.09,{timeout:30000,polling:30},axis,target,Math.sign(delta));await p.keyboard.up(key);}await sleep(100);}
try{
 const context=await browser.createBrowserContext();const p=await context.newPage();await p.setViewport({width:1440,height:900,deviceScaleFactor:1});p.on('pageerror',e=>report.errors.push(e.message));p.on('response',r=>{if(r.status()>=400)report.errors.push(`${r.status()} ${r.url()}`);});const start=Date.now();await p.goto('http://127.0.0.1:4173/game/',{waitUntil:'networkidle0'});await p.waitForFunction(()=>window.__READY__);const readyMs=Date.now()-start;check('Title is real DOM; boot has no autoplay audio',await p.evaluate(()=>!!document.querySelector('h1')&&window.__CTRL__.audio.state==='locked'));await shot(p,'desktop-title');
 await p.click('[data-open="how"]');await shot(p,'desktop-how');check('How-to opens', (await snap(p)).screen==='how');await p.click('#how .back');await p.click('[data-open="settings"]');await p.click('#reduced');await p.click('#mute');await p.$eval('#master',el=>{el.value=37;el.dispatchEvent(new Event('input',{bubbles:true}));});check('Settings and mute update real audio state',(await snap(p)).settings.master===37&&(await snap(p)).settings.mute);await shot(p,'desktop-settings');await p.click('#settings .back');await p.reload({waitUntil:'networkidle0'});check('Settings survive reload',(await snap(p)).settings.master===37&&(await snap(p)).settings.reduced);check('Reduced motion leaves title video unloaded',!(await snap(p)).video.src);
 await p.click('#startb');await p.waitForFunction(()=>window.__CTRL__.state.elapsed>.05);let s=await snap(p);check('Enter gives simulation control in under 1.5 seconds',s.startLatency<1500);check('Title video is stopped and unloaded in gameplay',s.video.paused&&!s.video.src);await shot(p,'desktop-game');
 const card=await p.$('#brightness'),rect=await card.boundingBox();await p.mouse.move(rect.x+45,rect.y+40);await p.mouse.down();await p.mouse.move(700,500,{steps:12});await p.mouse.up();check('Invalid remote drop returns the card',!(await snap(p)).state.installed);
 await p.keyboard.down('d');await p.waitForFunction(()=>window.__CTRL__.state.failure>0,{timeout:30000});await p.keyboard.up('d');await shot(p,'desktop-realign');await p.waitForFunction(()=>window.__CTRL__.state.resets===1&&!window.__CTRL__.state.failure,{timeout:10000});check('Void failure restores checkpoint once',(await snap(p)).state.z===6);
 await move(p,3.1,3);await move(p,-3.6,-1.4);s=await snap(p);check('Walking collects two real fragments',s.state.fragments.length===2);const target=s.socket;const r=await card.boundingBox();await p.mouse.move(r.x+r.width/2,r.y+r.height/2);await p.mouse.down();await p.mouse.move(target.x,target.y,{steps:20});await p.mouse.up();await p.waitForFunction(()=>window.__CTRL__.state.bridge===1,{timeout:10000});check('Real pointer drag installs BRIGHTNESS and reveals bridge',(await snap(p)).state.installed);await shot(p,'desktop-bridge');
 await p.keyboard.press('e');await p.waitForFunction(()=>!window.__CTRL__.state.installed);check('Installed control can be retrieved',(await snap(p)).state.moves===2);await p.focus('#brightness');await p.keyboard.press('Enter');await p.keyboard.press('e');await p.waitForFunction(()=>window.__CTRL__.state.bridge===1);check('Keyboard-only installation works',(await snap(p)).state.moves===3);
 await p.keyboard.press('Escape');const frozen=(await snap(p)).state.elapsed;await sleep(400);check('Pause freezes the simulation',(await snap(p)).state.elapsed===frozen);await shot(p,'desktop-pause');await p.click('#resume');await move(p,0,-12);check('Player crossed the restored bridge and reached checkpoint',(await snap(p)).state.checkpointReached);await move(p,2.8,-14);await move(p,0,-17);await p.keyboard.press('e');await p.waitForFunction(()=>window.__CTRL__.screen==='results',{timeout:15000});s=await snap(p);check('Atrium can be completed with all three fragments',s.state.won&&s.state.fragments.length===3);await shot(p,'desktop-results');check('Results disclose one sector rather than a finished three-chapter game',await p.$eval('#results',el=>el.textContent.includes('future chapter')));report.devices.push({name:'desktop',readyObservedMs:readyMs,startLatency:s.startLatency,metrics:s.metrics,transfer:await p.evaluate(()=>performance.getEntriesByType('resource').reduce((n,r)=>n+r.transferSize,0))});
 await p.click('#results .return-title');await p.waitForFunction(()=>window.__CTRL__.screen==='title');check('Return to title resets game state',!(await snap(p)).state.installed);await context.close();
 const mobile=await browser.createBrowserContext();const m=await mobile.newPage();await m.setViewport({width:390,height:844,deviceScaleFactor:1,isMobile:true,hasTouch:true});m.on('pageerror',e=>report.errors.push(e.message));m.on('response',r=>{if(r.status()>=400)report.errors.push(`${r.status()} ${r.url()}`);});await m.goto('http://127.0.0.1:4173/game/',{waitUntil:'networkidle0'});await m.waitForFunction(()=>window.__READY__);await shot(m,'mobile-title');await m.tap('#startb');await m.waitForFunction(()=>window.__CTRL__.state.elapsed>.05);check('Phone starts with a real touch and shows its joystick',(await snap(m)).settings.touch);await sleep(1200);await shot(m,'mobile-game');
 const client=await m.createCDPSession();async function touch(type,x,y,id=1){await client.send('Input.dispatchTouchEvent',{type,touchPoints:type==='touchEnd'?[]:[{x,y,id,radiusX:6,radiusY:6}]});}
 const jr=await (await m.$('#joystick')).boundingBox();const jx=jr.x+jr.width/2,jy=jr.y+jr.height/2;await touch('touchStart',jx,jy);await touch('touchMove',jx,jy-37);await m.waitForFunction(()=>window.__CTRL__.state.z<-.3,{timeout:30000});await touch('touchEnd',jx,jy-37);check('Real touch joystick moves Mara',(await snap(m)).state.z<0);await sleep(150);s=await snap(m);const cr=await (await m.$('#brightness')).boundingBox();await touch('touchStart',cr.x+cr.width/2,cr.y+cr.height/2);await touch('touchMove',s.socket.x,s.socket.y);await touch('touchEnd',s.socket.x,s.socket.y);await m.waitForFunction(()=>window.__CTRL__.state.bridge===1,{timeout:10000});check('Phone touch drag installs BRIGHTNESS',(await snap(m)).state.installed);await shot(m,'mobile-bridge');
 await m.tap('#pause-button');await m.tap('#pause [data-open="settings"]');await shot(m,'mobile-settings');check('Phone settings fit the viewport',await m.$eval('#settings .back',el=>el.getBoundingClientRect().bottom<=innerHeight));await m.tap('#settings .back');await m.tap('#resume');await m.setViewport({width:844,height:390,isMobile:true,hasTouch:true});await sleep(250);check('Resize retains a valid game state',(await snap(m)).screen==='hud');await m.setViewport({width:390,height:844,isMobile:true,hasTouch:true});report.devices.push({name:'390×844 touch emulation',startLatency:(await snap(m)).startLatency,metrics:(await snap(m)).metrics,physicalDevice:false});await mobile.close();check('No browser exceptions or failed runtime requests',report.errors.length===0);report.pass=true;
}catch(e){report.pass=false;report.failure=e.stack;console.error(e);process.exitCode=1;}finally{await fs.writeFile(`${dir}/report.json`,JSON.stringify(report,null,2));await browser.close();}
