import puppeteer from 'puppeteer';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {anchorAt,LOCKS,CORE,FRAGMENTS} from '../game/src/model.js';
const dir='production/recovery/browser';await fs.mkdir(dir,{recursive:true});const browser=await puppeteer.launch({headless:true,args:['--enable-unsafe-swiftshader','--disable-background-timer-throttling','--disable-renderer-backgrounding']});const report={date:new Date().toISOString(),checks:[],errors:[],devices:[]};const check=(name,value)=>{assert.ok(value,name);report.checks.push(name);console.log('PASS',name);};const sleep=ms=>new Promise(r=>setTimeout(r,ms));const snap=p=>p.evaluate(()=>window.__CTRL__);async function shot(p,name){await p.screenshot({path:`${dir}/${name}.png`});}
// Walk one axis at a time with real key presses. If a pedestal blocks the first order, try the other order once.
async function walk(p,x,z,order){for(const [axis,target,positive,negative]of order){const s=await snap(p),delta=target-s.state[axis];if(Math.abs(delta)<.10)continue;const key=delta>0?positive:negative;await p.keyboard.down(key);try{await p.waitForFunction((axis,target,dir)=>dir>0?window.__CTRL__.state[axis]>=target-.055:window.__CTRL__.state[axis]<=target+.055,{timeout:6000,polling:20},axis,target,Math.sign(delta));}catch{}await p.keyboard.up(key);}await sleep(180);}
async function move(p,x,z){const X=['x',x,'d','a'],Z=['z',z,'s','w'];await walk(p,x,z,[X,Z]);const s=await snap(p);if(Math.hypot(s.state.x-x,s.state.z-z)>.3)await walk(p,x,z,[Z,X]);}
async function installKeys(p,card='#brightness'){await p.focus(card);await p.keyboard.press('Enter');await p.keyboard.press('e');}
// Tutorial captures are only rewritten on request (RECOVERY_CAPTURE=1); a plain gate run never dirties game/media.
async function tutorialImage(p,name){if(process.env.RECOVERY_CAPTURE!=='1')return;const bytes=await p.screenshot({type:'webp',quality:85});await fs.writeFile(`game/media/tutorial/${name}.webp`,bytes);}
const PLATES=[{x:-2.8,z:-11.2},{x:.6,z:-11.6},{x:-1.2,z:-9}],FRACTURES=[{x:-2.7,z:-14},{x:0,z:-15},{x:1.8,z:-16.5}];
function observe(p){p.on('pageerror',e=>report.errors.push(e.message));p.on('response',r=>{if(r.status()>=400)report.errors.push(`${r.status()} ${r.url()}`);});}
try{
 const c=await browser.createBrowserContext(),p=await c.newPage();await p.setViewport({width:1440,height:900});observe(p);await p.goto('http://127.0.0.1:4173/game/');await p.waitForFunction(()=>window.__READY__);check('Title is real DOM and audio stays gesture-locked',(await snap(p)).audio.state==='locked');await p.waitForFunction(()=>document.getElementById('title-video').style.opacity==='1');await shot(p,'desktop-title-video');
 await p.click('[data-open="settings"]');await p.click('#reduced');await p.click('#mute');await p.focus('#master');await p.keyboard.press('Home');for(let i=0;i<37;i++)await p.keyboard.press('ArrowRight');check('Settings and mute update from keyboard and pointer',(await snap(p)).settings.master===37&&(await snap(p)).settings.mute);await shot(p,'desktop-settings');await p.click('#settings .back');await p.reload();await p.waitForFunction(()=>window.__READY__);check('Settings survive reload',(await snap(p)).settings.master===37&&(await snap(p)).settings.reduced);check('Reduced motion unloads title video',!(await snap(p)).video.src);await shot(p,'desktop-title-poster');
 await p.click('#startb');await p.waitForFunction(()=>window.__CTRL__.state.elapsed>.05);check('Enter gives simulation control in under 1.5 seconds',(await snap(p)).startLatency<1500);check('Video is stopped and unloaded in gameplay',!(await snap(p)).video.src&&(await snap(p)).video.paused);await sleep(600);await shot(p,'desktop-idle');check('Mara occupies 22–28% of gameplay height',(await snap(p)).metrics.maraFrameHeight>=22&&(await snap(p)).metrics.maraFrameHeight<=28);check('Only BRIGHTNESS is offered until the Kernel is restored',await p.$$eval('.control-card',els=>els.filter(e=>!e.hidden).length===1&&els.length===2));
 const card=await p.$('#brightness'),rect=await card.boundingBox();await p.mouse.move(rect.x+40,rect.y+40);await p.mouse.down();await p.mouse.move(1100,300,{steps:12});await p.mouse.up();check('Invalid remote drop returns the card',!(await snap(p)).state.installed);
 await p.keyboard.down('d');await p.waitForFunction(()=>window.__CTRL__.state.failure>0,{timeout:10000});await p.keyboard.up('d');await shot(p,'desktop-failure');await p.waitForFunction(()=>window.__CTRL__.state.resets===1&&!window.__CTRL__.state.failure);check('Void failure restores checkpoint exactly once',(await snap(p)).state.z===4.6);
 await move(p,2.7,3);await move(p,-3,-1);check('Original fragment collection remains functional',(await snap(p)).state.fragments.length===2);await move(p,.8,-1.25);const target=(await snap(p)).socket;const r=await card.boundingBox();await p.mouse.move(r.x+r.width/2,r.y+r.height/2);await p.mouse.down();await p.mouse.move(target.x-35,target.y+35,{steps:15});await shot(p,'desktop-drag');await tutorialImage(p,'pull');await p.mouse.move(target.x,target.y,{steps:6});await p.mouse.up();await sleep(180);await shot(p,'desktop-socket-lock');await tutorialImage(p,'install');check('Real pointer drag installs BRIGHTNESS',(await snap(p)).state.installed);check('Installation alone does not create the bridge',(await snap(p)).state.bridge===0);await p.click('[data-level="RADIANT"]');await p.waitForFunction(()=>window.__CTRL__.state.bridge===1);await shot(p,'desktop-bridge-complete');await tutorialImage(p,'restore');check('RADIANT completes the physical bridge',(await snap(p)).state.bridge===1);
 await p.keyboard.press('e');check('Installed control can be retrieved',!(await snap(p)).state.installed);await installKeys(p);await p.keyboard.press('3');await sleep(65);await p.waitForFunction(()=>window.__CTRL__.state.bridge===1);check('Keyboard-only installation and value selection work',(await snap(p)).state.installed&&(await snap(p)).state.brightness==='RADIANT');
 await p.keyboard.press('Escape');const frozen=(await snap(p)).state.elapsed;await sleep(350);check('Pause freezes simulation',(await snap(p)).state.elapsed===frozen);await shot(p,'desktop-pause');await p.click('#pause [data-open="how"]');for(let i=1;i<=4;i++){await p.waitForFunction(()=>document.getElementById('lesson-image').complete&&document.getElementById('lesson-image').naturalWidth>0);await shot(p,`desktop-how-${i}`);if(i<4)await p.keyboard.press('ArrowRight');}check('Tutorial has four steps with real images and keyboard navigation',await p.$eval('#lesson-progress',e=>e.textContent==='04 / 04')&&await p.$eval('#lesson-kicker',e=>e.textContent.includes('WEIGH')));await p.click('#how .back');await p.click('#resume');
 await move(p,0,-9);check('Crossing reaches the relay checkpoint',(await snap(p)).state.stage===1);await move(p,1.1,-9.4);await p.keyboard.press('e');await installKeys(p);await p.keyboard.press('1');await sleep(65);check('DIM reveals the archive sequence',(await snap(p)).state.glyphSeen&&await p.$eval('#puzzle-label',e=>e.textContent.includes('◇')));await p.keyboard.press('3');await sleep(65);check('RADIANT hides the glyph answer',await p.$eval('#puzzle-label',e=>!e.textContent.includes('◇')));await p.keyboard.press('2');await sleep(65);await move(p,PLATES[1].x,PLATES[1].z);await shot(p,'desktop-read-wrong-plate');{const s=(await snap(p)).state;check('Wrong plate resets the order in place without a realignment',s.missteps===1&&s.resets===1&&!s.readSolved&&s.glyphInput.length===0);}await p.waitForFunction(()=>window.__CTRL__.state.misstep===0);for(const i of [2,0,1]){await move(p,-1.2,-10.4);await move(p,PLATES[i].x,PLATES[i].z);}check('Walking the remembered order opens the next threshold',(await snap(p)).state.readSolved);await shot(p,'desktop-read-restored');
 await move(p,0,-13.7);check('Second checkpoint advances to stabilization',(await snap(p)).state.stage===2);await move(p,2.8,-14);await move(p,-.8,-15.2);await p.keyboard.press('e');await installKeys(p);await p.keyboard.press('1');await sleep(65);check('DIM reveals three corruption nodes',(await snap(p)).state.nodesSeen);await shot(p,'desktop-stabilize-dim');await p.keyboard.press('2');await sleep(65);for(const f of FRACTURES)await move(p,f.x,f.z);check('Walking into the fractures under BALANCED seals all three',(await snap(p)).state.cleared.length===3&&(await snap(p)).state.resets===1);await move(p,-.8,-15.2);await p.keyboard.press('3');await sleep(65);await p.waitForFunction(()=>window.__CTRL__.state.restoration>.5,{timeout:10000});await shot(p,'desktop-kernel-restored');await p.waitForFunction(()=>window.__CTRL__.state.stage===3,{timeout:10000});await sleep(400);await shot(p,'desktop-well-briefing');
 {const s=(await snap(p)).state;check('Kernel restoration returns BRIGHTNESS to hand and yields GRAVITY',s.hasGravity&&!s.installed&&!s.won&&await p.$eval('#gravity',e=>!e.hidden)&&await p.$eval('#sector-label',e=>e.textContent==='SECTOR 02'));}
 await move(p,0,-17.8);await move(p,0,-21.5);check('The stair below the Kernel lands in the Well',(await snap(p)).state.landed);await move(p,-2.4,-24.4);await move(p,.9,-22.6);
 {const g=(await snap(p)).gravitySocket,gc=await(await p.$('#gravity')).boundingBox();await p.mouse.move(gc.x+gc.width/2,gc.y+gc.height/2);await p.mouse.down();await p.mouse.move(g.x-30,g.y+30,{steps:12});await shot(p,'desktop-well-drag');await p.mouse.move(g.x,g.y,{steps:6});await p.mouse.up();await sleep(180);}
 check('Real pointer drag installs GRAVITY in the violet socket',(await snap(p)).state.gInstalled&&(await snap(p)).state.gSocket===3);check('Slabs stay sunk until LOW',(await snap(p)).state.lift===0);await p.keyboard.press('4');await sleep(65);await p.waitForFunction(()=>window.__CTRL__.state.lift===1,{timeout:5000});await shot(p,'desktop-well-lift');check('LOW gravity lifts the slabs and slows Mara',(await snap(p)).state.gravity==='LOW'&&(await snap(p)).state.lowCharge<9);
 await move(p,0,-22.6);await move(p,0,-31.3);check('Crossing the slabs before the charge spends reaches the anchor deck',(await snap(p)).state.stage===4&&(await snap(p)).state.resets===1);
 await move(p,.6,-32.5);await p.keyboard.press('e');check('GRAVITY can be brought forward from the landing socket',!(await snap(p)).state.gInstalled);await installKeys(p,'#gravity');await p.keyboard.press('6');await sleep(65);check('HEAVY freezes the drifting anchors',(await snap(p)).state.gravity==='HEAVY'&&(await snap(p)).state.gSocket===4);await shot(p,'desktop-well-anchors');
 for(let i=0;i<3;i++){const a=anchorAt((await snap(p)).state,i);await move(p,a.x,a.z);}check('Pinning all three anchors under HEAVY opens the stair',(await snap(p)).state.anchored&&(await snap(p)).state.resets===1);await shot(p,'desktop-well-anchored');
 await move(p,0,-37.1);await move(p,0,-37.9);check('The anchored stair reaches the core checkpoint',(await snap(p)).state.stage===5);await move(p,.9,-39.5);await installKeys(p);check('BRIGHTNESS installs at the core beside the gravity socket',(await snap(p)).state.installedSocket===5);await p.keyboard.press('e');await installKeys(p,'#gravity');check('Both controls sit in adjacent sockets',(await snap(p)).state.gSocket===6);
 await p.keyboard.press('1');await sleep(65);check('DIM alone does not show the locks',!(await snap(p)).state.locksSeen);await p.keyboard.press('6');await sleep(65);check('DIM + HEAVY shows the core locks',(await snap(p)).state.locksSeen);await shot(p,'desktop-well-locks');for(const l of LOCKS)await move(p,l.x,l.z);await move(p,FRAGMENTS[4].x,FRAGMENTS[4].z);check('Walking the three locks pins them and the last fragment is reachable',(await snap(p)).state.locks.length===3&&(await snap(p)).state.fragments.length===5);
 await move(p,.9,-39.5);await p.keyboard.press('3');await sleep(65);await p.keyboard.press('4');await sleep(65);await p.waitForFunction(()=>window.__CTRL__.state.core===1,{timeout:5000});await shot(p,'desktop-well-core');check('RADIANT + LOW raises the core',(await snap(p)).state.core===1);await p.keyboard.down('a');try{await p.waitForFunction(()=>window.__CTRL__.state.restoration>0,{timeout:5000,polling:20});}finally{await p.keyboard.up('a');}await shot(p,'desktop-well-sync');await p.waitForFunction(()=>window.__CTRL__.state.won,{timeout:10000});await p.waitForFunction(()=>window.__CTRL__.screen==='results');await shot(p,'desktop-results');const s=await snap(p);check('Complete win loop preserves all five fragments',s.state.won&&s.state.fragments.length===5);check('Results expose deployments and replay controls',await p.$eval('#results',e=>e.textContent.includes('Control deployments')&&e.textContent.includes('0 / 5')===false));report.devices.push({name:'desktop',readyMs:s.readyTime,posterMs:s.posterVisible,startLatency:s.startLatency,metrics:s.metrics,transferBytes:await p.evaluate(()=>performance.getEntriesByType('resource').reduce((n,r)=>n+r.transferSize,0))});await p.click('#replay');check('Replay resets the entire sequence',(await snap(p)).state.stage===0&&!(await snap(p)).state.won);await p.keyboard.press('Escape');await p.click('#pause .return-title');check('Return to title works',(await snap(p)).screen==='title');await c.close();
 const mc=await browser.createBrowserContext(),m=await mc.newPage();await m.setViewport({width:390,height:844,deviceScaleFactor:1,isMobile:true,hasTouch:true});observe(m);await m.goto('http://127.0.0.1:4173/game/');await m.waitForFunction(()=>window.__READY__);await shot(m,'mobile-title');check('Mobile uses portrait poster and no video',await m.$eval('#poster',e=>e.currentSrc.includes('mobile-poster'))&&!(await snap(m)).video.src);await m.tap('[data-open="how"]');for(let i=1;i<=4;i++){await m.waitForFunction(()=>document.getElementById('lesson-image').complete);await shot(m,`mobile-how-${i}`);if(i<4)await m.tap('#lesson-next');}check('Mobile tutorial controls fit',await m.$eval('#lesson-next',e=>e.getBoundingClientRect().bottom<innerHeight));await m.tap('#how .back');await m.tap('#startb');await m.waitForFunction(()=>window.__CTRL__.state.elapsed>.05);await sleep(700);await shot(m,'mobile-gameplay');check('Real touch starts the game',(await snap(m)).settings.touch);
 const client=await m.createCDPSession();async function touch(type,x,y){await client.send('Input.dispatchTouchEvent',{type,touchPoints:type==='touchEnd'?[]:[{x,y,id:1,radiusX:6,radiusY:6}]});}const jr=await(await m.$('#joystick')).boundingBox(),jx=jr.x+jr.width/2,jy=jr.y+jr.height/2;await touch('touchStart',jx,jy);await touch('touchMove',jx,jy-37);await m.waitForFunction(()=>window.__CTRL__.state.z<-.1,{timeout:15000});await touch('touchEnd',jx,jy-37);check('Touch joystick moves Mara',(await snap(m)).state.z<0);await sleep(200);const ms=await snap(m),cr=await(await m.$('#brightness')).boundingBox();await touch('touchStart',cr.x+cr.width/2,cr.y+cr.height/2);await touch('touchMove',ms.socket.x,ms.socket.y);await touch('touchEnd',ms.socket.x,ms.socket.y);check('Touch drag installs the real card',(await snap(m)).state.installed);await m.tap('[data-level="RADIANT"]');await m.waitForFunction(()=>window.__CTRL__.state.bridge===1);await shot(m,'mobile-bridge');check('Touch changes brightness and restores the bridge',(await snap(m)).state.bridge===1);await m.tap('#pause-button');await m.tap('#pause [data-open="settings"]');await shot(m,'mobile-settings');check('Mobile settings fit',await m.$eval('#settings .back',e=>e.getBoundingClientRect().bottom<=innerHeight));await m.tap('#settings .back');await m.tap('#resume');await m.setViewport({width:844,height:390,isMobile:true,hasTouch:true});await sleep(250);check('Orientation change retains gameplay',(await snap(m)).screen==='hud');report.devices.push({name:'390×844 touch emulation',physicalDevice:false,startLatency:(await snap(m)).startLatency,metrics:(await snap(m)).metrics});await mc.close();check('No browser exceptions or missing requests',report.errors.length===0);report.pass=true;
}catch(e){report.pass=false;report.failure=e.stack;console.error(e);process.exitCode=1;}finally{await fs.writeFile(`${dir}/report.json`,JSON.stringify(report,null,2));await browser.close();}
